Docs building and deployments updates
* Add docs building and deployment to all snapshot releases. It's done
without tagging a new version; i.e. the deployment will update the
"next" version only.
* Switch all docs building to node-20
* Update the old ways to output in GH actions with the new one
  ($GITHUB_OUTPUT)
* Cleanup unused code
* Replace TAG-AND-RELEASE flag to docs building with TAG.
* Update all templates with the product-key example.

Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/csharp-app-snapshot.yml b/.github/workflows/csharp-app-snapshot.yml
--- a/.github/workflows/csharp-app-snapshot.yml
+++ b/.github/workflows/csharp-app-snapshot.yml
@@ -27,6 +27,14 @@ on:
         required: false
         type: string
         default: "src"
+      product-key:
+        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+        required: true
+        type: string
+      product-repo:
+        description: 'Product repository used for downloading snapshot docs'
+        required: true
+        type: string
       configuration:
         description: 'Configuration'
         required: false
@@ -57,6 +65,8 @@ jobs:
     env:
       LICENCE_CHECK: ${{ inputs.licencecheck }}
     runs-on: windows-2019
+    outputs:
+      docs-present: ${{ steps.docs.outputs.present }}
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
@@ -93,9 +103,9 @@ jobs:
         new_info_version_date=$(date '+%d%m%Y%H%M%S')
         sed -i "s|$info_version_date|$new_info_version_date|g" ${{ inputs.version_file }}
         info_version=$(cat ${{ inputs.version_file }} | grep "AssemblyInformationalVersion(\"[0-9]\+\.[0-9]\+\.[0-9]\+.*\")" | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\++build[0-9]\+")
-        echo "info_version=$info_version" >> $GITHUB_OUTPUT
+        echo "info_version=$info_version" >> ${GITHUB_ENV}
         artifact_id=$(cat ${{ inputs.version_file }} | grep "AssemblyTitle" | egrep -o "\"[A-Za-z0-9\-]+\"" | tr -d '"')
-        echo "artifact_id=$artifact_id" >> $GITHUB_OUTPUT
+        echo "artifact_id=$artifact_id" >> ${GITHUB_ENV}
 
     - name: Add ZepBen Nuget Repo credentials
       run: nuget sources update -Name "ZepBen" -username "${{ secrets.NEXUS_USERNAME }}" -password "${{ secrets.NEXUS_PASSWORD }}" -configFile "Nuget.Config"
@@ -127,5 +137,105 @@ jobs:
       id: upload
       uses: actions/upload-artifact@v3
       with:
-        name: ${{ steps.update-info-version.outputs.artifact_id }}-${{ steps.update-info-version.outputs.info_version }}
-        path: ${{ steps.upload_path.outputs.path }}
+        name: ${{ env.artifact_id }}-${{ env.info_version }}
+        path: ${{ env.artifact_id }}/bin/Release/
+
+    - name: Check if docs present
+      id: docs
+      run: |
+        if [ -d docs ]; then
+          echo "Docs folder found, will run the build-docs job"
+          echo "present=yes" >> "${GITHUB_OUTPUT}"
+          echo "present=yes" >> "${GITHUB_ENV}"
+        else
+          echo "Docs folder not found, will skip the build-docs"
+        fi
+
+    - name: Work around git permission issue
+      run: |
+        dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+        git config --global --add safe.directory /__w/$dname/$dname
+      shell: sh
+
+    - name: Check doc build artifacts are ignored
+      if: ${{ env.present == 'yes' }}
+      shell: sh {0}
+      run: |
+        # Make sure directories are properly ignored
+        # docs/node_modules
+        git check-ignore -q docs/node_modules 
+        if [ $? != 0 ]; then
+            echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+            echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+            exit 1
+        fi
+
+        # docs/build
+        git check-ignore -q docs/build 
+        if [ $? != 0 ]; then
+            echo "ERROR! Make sure to add 'docs/build' to .gitignore"
+            echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
+            exit 1
+        fi
+
+  build-docs:
+    runs-on: ubuntu-latest
+    needs: [build-app]
+    if: ${{ needs.build-app.outputs.docs-present == 'yes' }}
+    outputs:
+      artifact-uploaded: ${{ steps.artifact.outputs.uploaded }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache-dependency-path: docs/package-lock.json
+          cache: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          TAG: false
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - name: Failed build
+        if: steps.build.outcome == 'failure'
+        run: |
+          echo "There was an error in the docusaurus build above. Docs are not pushed"
+          echo " :boom: There was an error in the docusaurus build step. Current docs are not published" >> ${GITHUB_STEP_SUMMARY}
+        shell: sh
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: bash
+
+      - uses: actions/upload-artifact@v3
+        if: steps.build.outcome == 'success'
+        id: upload
+        with:
+          name: docs.zip
+          path: docs.zip
+
+      - if: steps.upload.outcome == 'success'
+        id: artifact
+        run:
+          echo "uploaded=yes" >> "${GITHUB_OUTPUT}"
+
+  deploy-docs:
+    runs-on: ubuntu-latest
+    needs: [build-docs]
+    if: ${{ needs.build-docs.outputs.artifact-uploaded == 'yes' }}
+    steps:
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v2
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product_key": "${{ inputs.product-key }}", "download_url": "${{inputs.product-repo}}"}'
diff --git a/.github/workflows/npm-app-snapshot-release.yml b/.github/workflows/npm-app-snapshot-release.yml
--- a/.github/workflows/npm-app-snapshot-release.yml
+++ b/.github/workflows/npm-app-snapshot-release.yml
@@ -8,11 +8,6 @@ on:
         required: false
         type: boolean
         default: true
-      build-docs:
-        description: 'Repo has docusaurus docs'
-        required: false
-        type: boolean
-        default: false
       licencecheck:
         description: 'Need to check licence headers/files'
         required: false
@@ -23,6 +18,14 @@ on:
         required: false
         type: string
         default: "src"
+      product-key:
+        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+        required: true
+        type: string
+      product-repo:
+        description: 'Product repository used for downloading snapshot docs'
+        required: true
+        type: string
     secrets:
       NEXUS_NPM_REPO:
         required: true
@@ -43,9 +46,8 @@ jobs:
       LICENCE_CHECK: ${{ inputs.licencecheck }}
     runs-on: ubuntu-latest
     outputs:
-      artifact: ${{ steps.build.outputs.artifact }}
-      version: ${{ steps.build.outputs.version }}
-    container: node:16-alpine
+      docs-present: ${{ steps.docs.outputs.present }}
+    container: node:14-alpine
     steps:
     - name: Install Dependencies
       run: |
@@ -91,59 +93,107 @@ jobs:
         echo "NPM is sensitive to .npmrc formatting; check that it has a newline at the end!!!"
         npm ci --unsafe-perm
         npm run prod
-        version=$(jq -r .version package.json)
+        # version=$(jq -r .version package.json)
         artifactId=$(jq -r .name package.json)
         artifact="$artifactId-$version-SNAPSHOT.tar.bz2"
         tar jcvf "$artifact" -C dist .
-        echo "version=$version" >> $GITHUB_OUTPUT
-        echo "artifact=$artifact" >> $GITHUB_OUTPUT
+        echo "artifact=$artifact" >> ${GITHUB_ENV}
 
     - uses: actions/upload-artifact@v3
       if: steps.build.outcome == 'success'
       with:
-          name: ${{ steps.build.outputs.artifact }}
-          path: ${{ steps.build.outputs.artifact }}
+          name: ${{ env.artifact }}
+          path: ${{ env.artifact }}
+
+    - name: Check if docs present
+      id: docs
+      run: |
+        if [ -d docs ]; then
+          echo "Docs folder found, will run the build-docs job"
+          echo "present=yes" >> "${GITHUB_OUTPUT}"
+          echo "present=yes" >> "${GITHUB_ENV}"
+        else
+          echo "Docs folder not found, will skip the build-docs"
+        fi
+
+    - name: Work around git permission issue
+      run: |
+        dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+        git config --global --add safe.directory /__w/$dname/$dname
+      shell: sh
+
+    - name: Check doc build artifacts are ignored
+      if: ${{ env.present == 'yes' }}
+      shell: sh {0}
+      run: |
+        # Make sure directories are properly ignored
+        # docs/node_modules
+        git check-ignore -q docs/node_modules 
+        if [ $? != 0 ]; then
+            echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+            echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+            exit 1
+        fi
+
+        # docs/build
+        git check-ignore -q docs/build 
+        if [ $? != 0 ]; then
+            echo "ERROR! Make sure to add 'docs/build' to .gitignore"
+            echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
+            exit 1
+        fi
 
   build-docs:
     runs-on: ubuntu-latest
-    if: ${{ inputs.build-docs }}
-    container: node:16-alpine
+    needs: [build-artifact]
+    if: ${{ needs.build-artifact.outputs.docs-present == 'yes' }}
+    outputs:
+      artifact-uploaded: ${{ steps.artifact.outputs.uploaded }}
     steps:
-      - name: Install Dependencies
-        run: |
-          apk add tar 
-
-      - name: Cache nodejs deps
-        uses: actions/cache@v3
-        with:
-          path: ~/.npm
-          key: npm
-
       - uses: actions/checkout@v3
 
-      - name: create .npmrc
-        run: | 
-          rm -rf ~/.npmrc
-          echo "@zepben:registry=${{ secrets.NEXUS_NPM_REPO }}" >> ~/.npmrc
-          echo "//mavenrepo.zepben.com/repository/zepben-npm/:_authToken=${{ secrets.CI_NPM_TOKEN }}" >> ~/.npmrc
-          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_GITHUB_TOKEN }}" >> ~/.npmrc
-          echo "\n" >> ~/.npmrc
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache-dependency-path: docs/package-lock.json
+          cache: npm
 
-      - name: Build docs
-        id: docs
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          TAG: false
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - name: Failed build
+        if: steps.build.outcome == 'failure'
         run: |
-          cd docs
-          npm ci --unsafe-perm
-          npm run build
+          echo "There was an error in the docusaurus build above. Docs are not pushed"
+          echo " :boom: There was an error in the docusaurus build step. Current docs are not published" >> ${GITHUB_STEP_SUMMARY}
+        shell: sh
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: bash
 
       - uses: actions/upload-artifact@v3
-        if: steps.docs.outcome == 'success' 
+        if: steps.build.outcome == 'success'
+        id: upload
         with:
-          name: docs
-          path: docs/build/
+          name: docs.zip
+          path: docs.zip
+
+      - if: steps.upload.outcome == 'success'
+        id: artifact
+        run:
+          echo "uploaded=yes" >> "${GITHUB_OUTPUT}"
 
   update-snapshot-version:
-    needs: [build-artifact, build-docs]
+    needs: [build-artifact]
     container: zepben/pipeline-basic
     runs-on: ubuntu-latest
     env:
@@ -165,3 +215,17 @@ jobs:
       - name: Update snapshot version
         run: |
           /scripts/update-version.sh --js --snapshot package.json
+
+  deploy-docs:
+    runs-on: ubuntu-latest
+    needs: [build-docs]
+    if: ${{ needs.build-docs.outputs.artifact-uploaded == 'yes' }}
+    steps:
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v2
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product_key": "${{ inputs.product-key }}", "download_url": "${{inputs.product-repo}}"}'
+
