Split repo check and build workflows for csharp
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/csharp-app-snapshot.yml b/.github/workflows/csharp-app-snapshot.yml
--- a/.github/workflows/csharp-app-snapshot.yml
+++ b/.github/workflows/csharp-app-snapshot.yml
@@ -63,12 +63,74 @@ on:
         value: ${{ jobs.build.outputs.version }}
 
 jobs:
+  checks:
+    runs-on: ubuntu-latest
+    container: zepben/pipeline-basic
+    outputs: 
+      docs-present: ${{ steps.docs.outputs.present }}
+    env:
+      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          token: ${{ env.GITHUB_TOKEN }}
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - name: Cache licence-check
+        uses: actions/cache@v4
+        with:
+          path: /lc
+          key: lcc
+
+      - name: Check licence
+        uses: zepben/licence-check-action@main
+        with:
+          LC_URL: ${{ secrets.LC_URL }}
+          PATH: ${{ inputs.sourcepath }}
+
+      - name: Check if docs present
+        id: docs
+        shell: bash
+        run: |
+          if [ -d docs ]; then
+            echo "Docs folder found, will run the build-docs job"
+            echo "present=yes" >> "${GITHUB_OUTPUT}"
+            echo "present=yes" >> "${GITHUB_ENV}"
+          else
+            echo "Docs folder not found, will skip the build-docs"
+          fi
+
+      - name: Check doc build artifacts are ignored
+        if: ${{ env.present == 'yes' }}
+        shell: sh {0}
+        run: |
+          # Make sure directories are properly ignored
+          # docs/node_modules
+          git check-ignore -q docs/node_modules 
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+              exit 1
+          fi
+
+          # docs/build
+          git check-ignore -q docs/build 
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/docs' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
+              exit 1
+          fi
+
   build:
     runs-on: windows-2019
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     outputs:
-      docs-present: ${{ steps.docs.outputs.present }}
       version: ${{ steps.update-info-version.outputs.info_version }}
     steps:
     - name: Checkout Code
@@ -79,18 +141,6 @@ jobs:
         dname=$(echo ${{github.repository}} | cut -d'/' -f2)
         git config --global --add safe.directory /__w/$dname/$dname
       shell: sh
-
-    - name: Cache licence-check
-      uses: actions/cache@v4
-      with:
-        path: /lc
-        key: lcc
-
-    - name: Check licence
-      uses: zepben/licence-check-action@main
-      with:
-        LC_URL: ${{ secrets.LC_URL }}
-        PATH: ${{ inputs.sourcepath }}
 
     - name: Setup NuGet
       uses: NuGet/setup-nuget@v1.0.5
@@ -146,44 +196,6 @@ jobs:
       with:
         name: ${{ env.artifact_id }}-${{ env.info_version }}
         path: ${{ env.artifact_id }}/bin/Release/
-
-    - name: Check if docs present
-      id: docs
-      run: |
-        if [ -d docs ]; then
-          echo "Docs folder found, will run the build-docs job"
-          echo "present=yes" >> "${GITHUB_OUTPUT}"
-          echo "present=yes" >> "${GITHUB_ENV}"
-        else
-          echo "Docs folder not found, will skip the build-docs"
-        fi
-
-    - name: Work around git permission issue
-      run: |
-        dname=$(echo ${{github.repository}} | cut -d'/' -f2)
-        git config --global --add safe.directory /__w/$dname/$dname
-      shell: sh
-
-    - name: Check doc build artifacts are ignored
-      if: ${{ env.present == 'yes' }}
-      shell: sh {0}
-      run: |
-        # Make sure directories are properly ignored
-        # docs/node_modules
-        git check-ignore -q docs/node_modules
-        if [ $? != 0 ]; then
-            echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
-            echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
-            exit 1
-        fi
-
-        # docs/build
-        git check-ignore -q docs/build
-        if [ $? != 0 ]; then
-            echo "ERROR! Make sure to add 'docs/build' to .gitignore"
-            echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
-            exit 1
-        fi
 
   build-docs:
     runs-on: ubuntu-latest
