Ewb 4089 build docs as part of all workflows (#16)
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/csharp-app-release-with-docs.yml b/.github/workflows/csharp-app-release-with-docs.yml
--- a/.github/workflows/csharp-app-release-with-docs.yml
+++ b/.github/workflows/csharp-app-release-with-docs.yml
@@ -1,11 +1,21 @@
-name: NPM Static App Release
+name: CSharp App Release With Docs
 
 on: 
   workflow_call:
     inputs:
-      product-key:
-        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+      test_files:
+        description: 'Test dll output files separated by space.'
+        required: false
+        default: ''
+        type: string
+      version_file:
+        description: 'Project file for updating version.'
         required: true
+        type: string
+      changelog:
+        description: 'Path to the changelog.'
+        default: 'changelog.md'
+        required: false
         type: string
       private:
         description: 'Calling workflow from a private repo'
@@ -22,12 +32,27 @@ on:
         required: false
         type: string
         default: "src"
+      configuration:
+        description: 'Configuration'
+        required: false
+        type: string
+        default: "Release"
+      platform:
+        description: 'Platform'
+        required: false
+        type: string
+        default: "x64"
+      binary_path:
+        description: 'Path to the binaries.'
+        required: false
+        type: string
+        default: ""
     secrets:
-      NEXUS_NPM_REPO:
-        required: true
-      CI_NPM_TOKEN:
-        required: true
       CI_GITHUB_TOKEN:
+        required: true
+      NEXUS_USERNAME:
+        required: true
+      NEXUS_PASSWORD: 
         required: true
       SLACK_NOTIFICATION:
         required: false
@@ -36,16 +61,20 @@ on:
       LC_URL: 
         required: false
 
+
 jobs:
   release-checks:
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
-    continue-on-error: false
     env:
       LICENCE_CHECK: ${{ inputs.licencecheck }}
+      DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
       SLACK_NOTIFICATION: YES
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+    outputs:
+      version: ${{ steps.check.outputs.version }}
+      artifact_id: ${{ steps.check.outputs.artifact_id }}
     steps:
       - uses: actions/checkout@v3
         with:
@@ -72,9 +101,83 @@ jobs:
           PATH: ${{ inputs.sourcepath }}
 
       - name: Release checks and update version for release
+        id: check
         run: |
-          /scripts/release-checks.sh --js package.json
-          /scripts/finalize-version.sh --js package.json changelog.md
+          /scripts/release-checks.sh --csharp ${{ inputs.version_file }}
+          /scripts/finalize-version.sh --csharp ${{ inputs.version_file }} ${{ inputs.changelog }}
+          version=$(cat ${{ inputs.version_file }} | grep "AssemblyVersion(\"[0-9]\+\.[0-9]\+\.[0-9]\+\")" | grep -o "[0-9]\+\.[0-9]\+\.[0-9]")
+          echo "version=$version" >> $GITHUB_OUTPUT
+          artifact_id=$(cat ${{ inputs.version_file }} | grep "AssemblyTitle" | egrep -o "\"[A-Za-z0-9\-]+\"" | tr -d '"')
+          echo "artifact_id=$artifact_id" >> $GITHUB_OUTPUT
+        shell: bash
+
+  deploy:
+    needs: release-checks
+    runs-on: windows-2019
+    steps:
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - uses: actions/checkout@v3
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: bash
+      
+      - name: Setup NuGet
+        uses: NuGet/setup-nuget@v1.0.5
+      
+      - name: Setup MSBuild Path
+        uses: microsoft/setup-msbuild@v1
+
+      - name: Setup VSTest Path
+        uses: darenm/Setup-VSTest@v1.1.1
+
+      - name: Add ZepBen Nuget Repo credentials
+        run: nuget sources update -Name "ZepBen" -username "${{ secrets.NEXUS_USERNAME }}" -password "${{ secrets.NEXUS_PASSWORD }}" -configFile "Nuget.Config"
+      
+      - name: Restore NuGet Packages
+        run:   
+          msbuild /p:Configuration=${{ inputs.configuration }} /p:Platform=${{ inputs.platform }} /t:restore
+
+      - name: Build
+        id: build
+        run: msbuild /p:Configuration=${{ inputs.configuration }} /p:Platform=${{ inputs.platform }}
+
+      - name: Test
+        run: vstest.console.exe ${{ inputs.test_files }} /Platform:${{ inputs.platform }}
+
+      - name: Set upload path
+        id: upload_path
+        run: |
+          if [[ -z $BINARY_PATH ]]; then
+            echo "path=${{ needs.release-checks.outputs.artifact_id }}/bin/Release/" >> $GITHUB_OUTPUT
+          else
+            echo "path=$BINARY_PATH" >> $GITHUB_OUTPUT
+          fi
+        env:
+          BINARY_PATH: ${{ inputs.binary_path }}
+        shell: bash
+
+      - name: Upload Release
+        id: upload
+        uses: actions/upload-artifact@master
+        with:
+          name: ${{ needs.release-checks.outputs.artifact_id }}
+          path: ${{ steps.upload_path.outputs.path }}
+
+      - name: Delete release branch if deploy failed and fail
+        if: steps.build.outcome == 'failure' || steps.upload.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in one of the steps above."
+          exit 1
         shell: bash
 
   build-docs:
@@ -83,8 +186,6 @@ jobs:
     outputs:
       artifact: docs
     container: node:16-alpine
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
       - name: Install Git
         run: |
@@ -97,8 +198,6 @@ jobs:
         shell: sh
 
       - uses: actions/checkout@v3
-        with:
-          token: ${{ env.GITHUB_TOKEN }}
 
       - name: Checkout release branch
         run: |
@@ -122,7 +221,7 @@ jobs:
           NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
         continue-on-error: true
 
-      - uses: actions/upload-artifact@v3
+      - uses: actions/upload-artifact@master
         if: steps.build.outcome == 'success'
         with:
           name: docs
@@ -136,88 +235,11 @@ jobs:
           exit 1
         shell: sh
 
-  build-artifact:
-    needs: [build-docs, release-checks]
-    runs-on: ubuntu-latest
-    container: node:14-alpine
-    outputs:
-      artifact: ${{ steps.build.outputs.artifact }}
-      artifact-id: ${{ steps.build.outputs.artifact-id }}
-      version: ${{ steps.build.outputs.version }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-    steps:
-      - name: Install Dependencies
-        run: |
-          apk add jq tar alpine-conf git
-
-      - name: Cache nodejs deps
-        uses: actions/cache@v3
-        with:
-          path: ~/.npm
-          key: npm
-
-      - uses: actions/checkout@v3
-        with:
-          token: ${{ env.GITHUB_TOKEN }}
-
-      - name: Set timezone to Australia/ACT
-        run: |
-          setup-timezone -z Australia/ACT
-
-      - name: Work around git permission issue
-        run: |
-          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
-          git config --global --add safe.directory /__w/$dname/$dname
-        shell: sh
-
-      - name: Checkout release branch
-        run: |
-          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-          git fetch --all
-          git checkout release
-        shell: sh
-
-      - name: create .npmrc
-        run: | 
-          rm -rf .npmrc
-          echo "@zepben:registry=${{ secrets.NEXUS_NPM_REPO }}" >> .npmrc
-          echo "//mavenrepo.zepben.com/repository/zepben-npm/:_authToken=${{ secrets.CI_NPM_TOKEN }}" >> .npmrc
-          echo "\n" >> .npmrc
-
-      - name: build
-        id: build
-        run: |
-          npm ci --unsafe-perm
-          npm run prod
-          version=$(jq -r .version package.json)
-          artifactId=$(jq -r .name package.json)
-          artifact="$artifactId-$version.tar.bz2"
-          tar jcvf "$artifact" -C dist .
-          echo "::set-output name=version::$(echo $version)"
-          echo "::set-output name=artifact::$(echo $artifact)"
-        continue-on-error: true
-
-      - uses: actions/upload-artifact@v3
-        if: steps.build.outcome == 'success'
-        with:
-          name: ${{ steps.build.outputs.artifact }}
-          path: ${{ steps.build.outputs.artifact }}
-
-      - name: Fail build
-        if: steps.build.outcome == 'failure'
-        run: | 
-          git push origin -d release
-          echo "There was an error in the npm package command above."
-          exit 1
-        shell: sh
 
   create-release:
-    needs: [build-artifact]
+    needs: [deploy, release-checks, build-docs]
     runs-on: ubuntu-latest
-    outputs:
-      artifact: ${{ steps.merge.outputs.artifact }}
-      tag: ${{ steps.merge.outputs.tag }}
+    container: zepben/pipeline-basic
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
@@ -233,36 +255,49 @@ jobs:
 
       - name: Merge and Tag
         id: merge
-        run: | 
+        run: |
           git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
           git fetch --all
+          git branch -a
           git merge origin/release
           git push origin ${GITHUB_REF/refs\/heads\//}
-          version=$(jq -r .version package.json)
-          git tag "v$version"
+          git tag "v${{ needs.release-checks.outputs.version }}"
           git push --tags
-          echo "::set-output name=tag::$(echo v$version)"
-          echo "::set-output name=artifact::$(echo ${{ needs.build-artifact.outputs.artifact }})"
+          echo "tag=v${{ needs.release-checks.outputs.version }}" >> $GITHUB_OUTPUT
         shell: bash
         continue-on-error: true
 
-      - name: Fail
+      - name: Fail if any previous step failed
         if: steps.merge.outcome == 'failure'
-        run: | 
+        run: |
           git push origin -d release
           echo "There was an error in merging the branch. release branch was deleted."
           exit 1
         shell: bash
 
       - name: Download binary
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v2
         with:
-          name: ${{ needs.build-artifact.outputs.artifact }}
+          name: ${{ needs.release-checks.outputs.artifact_id }}
           path: built-artifacts
         continue-on-error: true
 
+      - name: Archive Release
+        uses: thedoctor0/zip-release@master
+        with:
+          type: zip
+          filename: ${{ needs.release-checks.outputs.artifact_id }}.zip
+          directory: built-artifacts
+
+      - name: Stat zip file
+        run: |
+          ls
+          echo "Y"
+          ls built-artifacts
+        shell: bash
+
       - name: Download docs
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v2
         with:
           name: docs
           path: docs-site
@@ -275,6 +310,16 @@ jobs:
         shell: bash
         continue-on-error: true
 
+      - name: Get latest changelog
+        id: changelog
+        run: |
+          lines=$(egrep -n "## \[[0-9]+\.[0-9]+\.[0-9]+\]" ${{ inputs.changelog }} | head -2 | cut -f1 -d:)
+          line1=$(echo "$lines" | head -1)
+          line2=$(echo "$lines" | tail -1)
+          cat ${{ inputs.changelog }} | tail -n +$((line1+1)) | head -n $((line2-line1-1)) > latest_changelog.txt
+        shell: bash
+        continue-on-error: true
+
       - name: Create Release and upload assets
         if: success()
         id: create_release
@@ -283,25 +328,17 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.merge.outputs.tag }}
-          body_path: changelog.txt
+          body_path: latest_changelog.txt
           draft: false
           prerelease: false
           files: |
-            built-artifacts/${{ needs.build-artifact.outputs.artifact }}
+            built-artifacts/${{ needs.release-checks.outputs.artifact_id }}.zip
             docs-site/docs-site.zip
         continue-on-error: true
 
-      - name: Deploy documentation
-        uses: peter-evans/repository-dispatch@v1
-        with:
-          token: ${{ secrets.CI_GITHUB_TOKEN }}
-          repository: ${{ secrets.DOCS_REPO }}
-          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
-          client-payload: '{"product_key": "${{ inputs.product-key }}", "download_url": "https://github.com/${{ github.repository }}/releases/download/${{ steps.merge.outputs.tag }}/docs-site.zip"}'
-        continue-on-error: true
 
   update-version:
-    needs: create-release
+    needs: [create-release]
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -322,5 +359,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          /scripts/update-version.sh --js --release package.json changelog.md
+          /scripts/update-version.sh --csharp --grow-changelog --release ${{ inputs.version_file }} ${{ inputs.changelog }}
         shell: bash
