Docs building and deployments updates (#20)
* Add docs building and deployment to all snapshot releases. It's done
without tagging a new version; i.e. the deployment will update the
"next" version only.
* Switch all docs building to node-20
* Update the old ways to output in GH actions with the new one
  ($GITHUB_OUTPUT)
* Cleanup unused code
* Replace TAG-AND-RELEASE flag to docs building with TAG.
* Update all templates with the product-key example.
* Add product-repo to templates

Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/csharp-build.yml b/.github/workflows/csharp-build.yml
--- a/.github/workflows/csharp-build.yml
+++ b/.github/workflows/csharp-build.yml
@@ -47,7 +47,7 @@ jobs:
   build-and-test:
     runs-on: windows-2019
     outputs: 
-      docs: ${{ steps.docs.outputs.present }}
+      docs-present: ${{ steps.docs.outputs.present }}
     env:
       LICENCE_CHECK: ${{ inputs.licencecheck }}
       DEBUG: ${{ secrets.DEBUG }}
@@ -102,15 +102,43 @@ jobs:
         if [ -d docs ]; then
           echo "Docs folder found, will run the build-docs job"
           echo "present=yes" >> "${GITHUB_OUTPUT}"
+          echo "present=yes" >> "${GITHUB_ENV}"
         else
           echo "Docs folder not found, will skip the build-docs"
+        fi
+
+    - name: Work around git permission issue
+      run: |
+        dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+        git config --global --add safe.directory /__w/$dname/$dname
+      shell: sh
+
+    - name: Check doc build artifacts are ignored
+      if: ${{ env.present == 'yes' }}
+      shell: sh {0}
+      run: |
+        # Make sure directories are properly ignored
+        # docs/node_modules
+        git check-ignore -q docs/node_modules 
+        if [ $? != 0 ]; then
+            echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+            echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+            exit 1
+        fi
+
+        # docs/build
+        git check-ignore -q docs/build 
+        if [ $? != 0 ]; then
+            echo "ERROR! Make sure to add 'docs/docs' to .gitignore"
+            echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
+            exit 1
         fi
 
   build-docs:
     runs-on: ubuntu-latest
     needs: build-and-test
-    if: ${{ needs.build-and-test.outputs.docs == 'yes' }}
-    container: node:16-alpine
+    if: ${{ needs.build-and-test.outputs.docs-present == 'yes' }}
+    container: node:20-alpine
     steps:
 
       - uses: actions/checkout@v3
@@ -119,6 +147,6 @@ jobs:
         id: build
         uses: zepben/docusaurus-action@main
         with:
-          TAG-AND-RELEASE: false
+          TAG: false
           NPM_REPO: ${{ secrets.NPM_REPO }}
           NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
diff --git a/.github/workflows/maven-app-snapshot.yml b/.github/workflows/maven-app-snapshot.yml
--- a/.github/workflows/maven-app-snapshot.yml
+++ b/.github/workflows/maven-app-snapshot.yml
@@ -18,6 +18,14 @@ on:
         required: false
         type: string
         default: "src"
+      product-key:
+        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+        required: true
+        type: string
+      product-repo:
+        description: 'Product repository used for downloading snapshot docs'
+        required: true
+        type: string
     secrets:
       CI_GITHUB_TOKEN:
         required: true
@@ -47,9 +55,7 @@ jobs:
     runs-on: ubuntu-latest
     container: zepben/pipeline-java
     outputs:
-      check_container_config: ${{ steps.check_container_config.outputs.files_exists }}
-      artifact_name: ${{ steps.build.outputs.version }}
-      artifact_path: ${{ steps.build.outputs.artifact-path }}
+      docs-present: ${{ steps.docs.outputs.present }}
 
     env:
       LICENCE_CHECK: ${{ inputs.licencecheck }}
@@ -87,9 +93,9 @@ jobs:
           artifactId=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/artifactId")
           version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
           artifact="${artifactId}-${version}.jar"
-          echo "::set-output name=version::$(echo $version)"
-          echo "::set-output name=artifactId::$(echo $artifactId)"
-          echo "::set-output name=artifact-path::$(echo target/$artifact)"
+          echo "version=$(echo $version)" >> ${GITHUB_ENV}
+          echo "artifactId=$(echo $artifactId)" >> ${GITHUB_ENV}
+          echo "artifact-path=$(echo target/$artifact)" >> ${GITHUB_ENV}
           mvn clean package -f pom.xml -P release -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.repo.url=$NEXUS_MAVEN_REPO
 
       - name: Upload coverage to Codecov
@@ -100,8 +106,95 @@ jobs:
 
       - uses: actions/upload-artifact@v3
         with:
-          name: ${{ steps.build.outputs.artifactId }}-${{ steps.build.outputs.version }}
-          path: ${{ steps.build.outputs.artifact-path }}
+          name: ${{ env.artifactId }}-${{ env.version }}
+          path: ${{ env.artifact-path }}
+
+      - name: Check if docs present
+        id: docs
+        run: |
+          if [ -d docs ]; then
+            echo "Docs folder found, will run the build-docs job"
+            echo "present=yes" >> "${GITHUB_OUTPUT}"
+            echo "present=yes" >> "${GITHUB_ENV}"
+          else
+            echo "Docs folder not found, will skip the build-docs"
+          fi
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - name: Check doc build artifacts are ignored
+        if: ${{ env.present == 'yes' }}
+        shell: sh {0}
+        run: |
+          # Make sure directories are properly ignored
+          # docs/node_modules
+          git check-ignore -q docs/node_modules 
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+              exit 1
+          fi
+
+          # docs/build
+          git check-ignore -q docs/build 
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/build' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
+              exit 1
+          fi
+
+  build-docs:
+    runs-on: ubuntu-latest
+    needs: [build-app]
+    if: ${{ needs.build-app.outputs.docs-present == 'yes' }}
+    outputs:
+      artifact-uploaded: ${{ steps.artifact.outputs.uploaded }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache-dependency-path: docs/package-lock.json
+          cache: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          TAG: false
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - name: Failed build
+        if: steps.build.outcome == 'failure'
+        run: |
+          echo "There was an error in the docusaurus build above. Docs are not pushed"
+          echo " :boom: There was an error in the docusaurus build step. Current docs are not published" >> ${GITHUB_STEP_SUMMARY}
+        shell: sh
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: bash
+
+      - uses: actions/upload-artifact@v3
+        if: steps.build.outcome == 'success'
+        id: upload
+        with:
+          name: docs.zip
+          path: docs.zip
+
+      - if: steps.upload.outcome == 'success'
+        id: artifact
+        run:
+          echo "uploaded=yes" >> "${GITHUB_OUTPUT}"
 
   update-snapshot-version:
     needs: [build-app]
@@ -129,3 +222,17 @@ jobs:
       - name: Update snapshot version
         run: |
           /scripts/update-version.sh --java --snapshot --maven pom.xml
+
+  deploy-docs:
+    runs-on: ubuntu-latest
+    needs: [build-docs]
+    if: ${{ needs.build-docs.outputs.artifact-uploaded == 'yes' }}
+    steps:
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v2
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product_key": "${{ inputs.product-key }}", "download_url": "${{inputs.product-repo}}"}'
+
diff --git a/.github/workflows/maven-lib-snapshot.yml b/.github/workflows/maven-lib-snapshot.yml
--- a/.github/workflows/maven-lib-snapshot.yml
+++ b/.github/workflows/maven-lib-snapshot.yml
@@ -18,6 +18,14 @@ on:
         required: false
         type: string
         default: "src"
+      product-key:
+        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+        required: true
+        type: string
+      product-repo:
+        description: 'Product repository used for downloading snapshot docs'
+        required: true
+        type: string
     secrets:
       CI_GITHUB_TOKEN:
         required: true
@@ -49,6 +57,52 @@ on:
         required: false
 
 jobs:
+
+  check-docs:
+    runs-on: ubuntu-latest
+    outputs:
+      docs-present: ${{ steps.docs.outputs.present }}
+    steps: 
+      - uses: actions/checkout@v3
+
+      - name: Check if docs present
+        id: docs
+        run: |
+          if [ -d docs ]; then
+            echo "Docs folder found, will run the build-docs job"
+            echo "present=yes" >> "${GITHUB_OUTPUT}"
+            echo "present=yes" >> "${GITHUB_ENV}"
+          else
+            echo "Docs folder not found, will skip the build-docs"
+          fi
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - name: Check doc build artifacts are ignored
+        if: ${{ env.present == 'yes' }}
+        shell: sh {0}
+        run: |
+          # Make sure directories are properly ignored
+          # docs/node_modules
+          git check-ignore -q docs/node_modules 
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
+              exit 1
+          fi
+
+          # docs/build
+          git check-ignore -q docs/build 
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/build' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
+              exit 1
+          fi
+
   deploy:
     runs-on: ubuntu-latest
     container: zepben/pipeline-java
@@ -77,16 +131,15 @@ jobs:
           LC_URL: ${{ secrets.LC_URL }}
           PATH: ${{ inputs.sourcepath }}
 
-
       - name: Set profile
         id: profile
         run: |
           priv=${{ inputs.private }}
           if [[ $priv == 'true' ]]
           then 
-            echo "::set-output name=profile::zepben-maven"; 
+            echo "PROFILE=zepben-maven" >> ${GITHUB_ENV} 
           else 
-            echo "::set-output name=profile::ossrh"
+            echo "PROFILE=ossrh" >> ${GITHUB_ENV}
           fi
 
       - name: Maven deploy to Central
@@ -102,11 +155,60 @@ jobs:
           OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
           GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
           GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
-          PROFILE: ${{ steps.profile.outputs.profile }}
+          PROFILE: ${{ env.PROFILE }}
 
       - name: Upload coverage to Codecov
         if: steps.build.outcome == 'success'
         uses: codecov/codecov-action@v2
+
+  build-docs:
+    runs-on: ubuntu-latest
+    needs: [check-docs]
+    if: ${{ needs.check-docs.outputs.docs-present == 'yes' }}
+    outputs:
+      artifact-uploaded: ${{ steps.artifact.outputs.uploaded }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache-dependency-path: docs/package-lock.json
+          cache: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          TAG: false
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - name: Failed build
+        if: steps.build.outcome == 'failure'
+        run: |
+          echo "There was an error in the docusaurus build above. Docs are not pushed"
+          echo " :boom: There was an error in the docusaurus build step. Current docs are not published" >> ${GITHUB_STEP_SUMMARY}
+        shell: sh
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: bash
+
+      - uses: actions/upload-artifact@v3
+        if: steps.build.outcome == 'success'
+        id: upload
+        with:
+          name: docs.zip
+          path: docs.zip
+
+      - if: steps.upload.outcome == 'success'
+        id: artifact
+        run:
+          echo "uploaded=yes" >> "${GITHUB_OUTPUT}"
 
   update-snapshot-version:
     needs: [deploy]
@@ -134,3 +236,17 @@ jobs:
       - name: Update snapshot version
         run: |
           /scripts/update-version.sh --java --snapshot --maven pom.xml
+
+  deploy-docs:
+    runs-on: ubuntu-latest
+    needs: [build-docs]
+    if: ${{ needs.build-docs.outputs.artifact-uploaded == 'yes' }}
+    steps:
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v2
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product_key": "${{ inputs.product-key }}", "download_url": "${{inputs.product-repo}}"}'
+
