Testing more ui
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/dev-dependencies-check.yml b/.github/workflows/dev-dependencies-check.yml
--- a/.github/workflows/dev-dependencies-check.yml
+++ b/.github/workflows/dev-dependencies-check.yml
@@ -14,10 +14,6 @@ on:
         type: string
         default: maven
 
-    outputs:
-      should_build: 
-        value: ${{ jobs.check-if-dev.outputs.should_build }}
-
 jobs:
   check-if-dev:
     runs-on: ubuntu-latest
@@ -29,8 +25,6 @@ jobs:
       DEV_NEXUS_PASSWORD: ${{ secrets.DEV_NEXUS_PASSWORD }}
       NEXUS_NPM_REPO: ${{ secrets.DEV_NEXUS_NPM_REPO }}
       CI_NPM_TOKEN: ${{ secrets.CI_NPM_DEV_TOKEN }}
-    outputs:
-      should_build: ${{ steps.test.output.should_build }}
     steps:
       - uses: actions/checkout@v7
         with:
@@ -60,15 +54,12 @@ jobs:
             res=$?
           else
             echo "Provided lang '${{ inputs.lang }}' is currently unsupported!"
-            echo "should_build=yes" >> "${GITHUB_OUTPUT}"
             exit
           fi
 
           if [[ $res == 0 ]]; then
             # Found dev dependencies, no need to build-and-test
             echo "Found dev dependencies, skipping project build"
-            echo -e "❌ Build Failed! Found the following dev dependencies:\n\n${out[@]}\n\nClear dev dependencies above when ready to merge." | gh pr comment ${{ github.event.pull_request.number }} --body-file -
-          else
-            # No dev dependencies, carry on
-            echo "should_build=yes" >> "${GITHUB_OUTPUT}"
+            echo -e "::error:: ❌ Build Failed! Found the following dev dependencies:\n\n${out[@]}\n\nClear dev dependencies above when ready to merge." | gh pr comment ${{ github.event.pull_request.number }} --body-file -
+            exit 1
           fi
