Support OSS and docs
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>

diff --git a/.github/workflows/maven-lib-release-with-docs.yml b/.github/workflows/maven-lib-release-with-docs.yml
--- a/.github/workflows/maven-lib-release-with-docs.yml
+++ b/.github/workflows/maven-lib-release-with-docs.yml
@@ -1,14 +1,30 @@
 # Note: default release notes file is docs/release.md.
-name: Maven Library Release
+name: Maven Library Release + Docs
 
 on: 
   workflow_call:
     inputs:
+      product-key:
+        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+        required: true
+        type: string
       private:
         description: 'Calling workflow from a private repo'
         required: true
         type: boolean
         default: true
+      licencecheck:
+        description: 'Need to check licence headers/files'
+        required: true
+        type: boolean
+        default: false
+      sourcepath:
+        description: 'Path to source directory (used for licence check)'
+        required: false
+        type: string
+        default: "src"
+
+
     secrets:
       CI_GITHUB_TOKEN:
         required: true
@@ -26,6 +42,8 @@ on:
         required: false
       SLACK_WEBHOOK:
         required: false
+      LC_URL:
+        required: false
 
 
 jobs:
@@ -33,6 +51,7 @@ jobs:
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
+      LICENCE_CHECK: ${{ inputs.licencecheck }}
       DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
       NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
@@ -64,8 +83,77 @@ jobs:
           echo "::set-output name=version::$(echo $version)"
         shell: bash
 
-  deploy:
+      - name: Cache licence-check
+        if: ${{ env.LICENCE_CHECK }}
+        uses: actions/cache@v3
+        with:
+          path: /lc
+          key: lcc
+
+      - name: Check licence
+        if: ${{ env.LICENCE_CHECK }}
+        uses: zepben/licence-check-action@main
+        with:
+          LC_URL: ${{ secrets.LC_URL }}
+          PATH: ${{ inputs.sourcepath }}
+
+  build-docs:
     needs: release-checks
+    runs-on: ubuntu-latest
+    outputs:
+      artifact: docs
+    container: node:12-alpine
+    steps:
+      - name: Install Git
+        run: |
+          apk add git
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - uses: actions/checkout@v3
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: sh
+
+      - name: Cache nodejs deps
+        uses: actions/cache@v2
+        with:
+          path: ~/.npm
+          key: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          VERSION: ${{ needs.release-checks.outputs.version }}
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - uses: actions/upload-artifact@master
+        if: steps.build.outcome == 'success'
+        with:
+          name: docs
+          path: docs/build/
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the docusaurus build above."
+          exit 1
+        shell: sh
+
+  deploy:
+    needs: [release-checks, build-docs]
     runs-on: ubuntu-latest
     outputs:
       artifact: ${{ steps.build.outputs.artifact }}
@@ -134,7 +222,7 @@ jobs:
         shell: bash
 
   create-release:
-    needs: [deploy, release-checks]
+    needs: [deploy, build-docs, release-checks]
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -164,7 +252,7 @@ jobs:
         shell: bash
         continue-on-error: true
 
-      - name: Fail if any previous step failed
+      - name: Delete release branch if merge failed and fail
         if: steps.merge.outcome == 'failure'
         run: |
           git push origin -d release
@@ -177,6 +265,20 @@ jobs:
         with:
           name: ${{ needs.deploy.outputs.artifact }}
           path: built-artifacts
+        continue-on-error: true
+
+      - name: Download docs
+        uses: actions/download-artifact@v2
+        with:
+          name: docs
+          path: docs-site
+        continue-on-error: true
+
+      - name: Zip documentation
+        run: |
+          cd docs-site
+          zip -r docs-site.zip .
+        shell: bash
         continue-on-error: true
 
       - name: Create Release and upload assets
@@ -192,8 +294,17 @@ jobs:
           prerelease: false
           files: |
             built-artifacts/${{ needs.deploy.outputs.artifact }}
+            docs-site/docs-site.zip
         continue-on-error: true
 
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v1
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product_key": "${{ inputs.product-key }}", "download_url": "https://github.com/${{ github.repository }}/releases/download/${{ steps.merge.outputs.tag }}/docs-site.zip"}'
+        continue-on-error: true
 
   update-version:
     needs: [create-release]
@@ -222,5 +333,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          /scripts/update-version.sh --java --grow-changelog --maven --release pom.xml changelog.md
+          /scripts/update-version.sh --java --maven --release pom.xml changelog.md
         shell: bash
