Refactor docs building
This change refactors how we build the documentation:

- Introduce a new workflow, build-docs that calls docusaurus-action and builds the docs.
  - It can also optionally "version tag" the docs
  - It can also "deploy" the docs (ie build the zipped archive for later deployment).
- It introduces the use of a new environment parameter called PRODUCT (to differentiate the deployment of evolve and ednar).

Other workflows were adapted to use this new flow.

The benefit of this refactoring is that all aspects of the documentation building are now controlled centrally via 1 flow.
Additionally, it allows to easily create separate, stand-alone docs-deployment flows.

Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/maven-app-release-with-docs.yml b/.github/workflows/maven-app-release-with-docs.yml
--- a/.github/workflows/maven-app-release-with-docs.yml
+++ b/.github/workflows/maven-app-release-with-docs.yml
@@ -1,5 +1,5 @@
 # Note: default release notes file is docs/release.md.
-name: Maven Library Release + Docs
+name: Maven App Release + Docs
 
 on: 
   workflow_call:
@@ -11,7 +11,7 @@ on:
         type: string
       private:
         description: 'Calling workflow from a private repo'
-        required: false
+        required: true
         type: boolean
         default: true
       sourcepath:
@@ -19,6 +19,11 @@ on:
         required: false
         type: string
         default: "src"
+
+    outputs:
+      version:
+        description: "The current released version."
+        value: ${{ jobs.release-checks.outputs.version }}
 
     secrets:
       CI_GITHUB_TOKEN:
@@ -39,24 +44,14 @@ on:
         required: false
       SLACK_WEBHOOK:
         required: false
-      LC_URL: 
-        required: false
-      ZEPBEN_GPG_KEY:
-        required: false
-      MAVEN_CENTRAL_USERNAME:
-        required: false
-      MAVEN_CENTRAL_PASSWORD:
-        required: false
-      GPG_KEY_ID:
-        required: false
-      GPG_KEY_PASSWORD:
-        required: false
       NPM_REPO:
         required: true
       DOCS_REPO:
         required: true
       DOCS_REPO_EVOLVE_WORKFLOW:
         required: true
+      LC_URL: 
+        required: false
 
 
 
@@ -107,7 +102,7 @@ jobs:
           /scripts/release-checks.sh --java --maven pom.xml
           /scripts/finalize-version.sh --java --maven pom.xml changelog.md
           version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
-          echo "version=$version" >> "${GITHUB_OUTPUT}"
+          echo "version=$(echo $version)" >> "${GITHUB_OUTPUT}"
         shell: bash
 
       - name: Check if docs present
@@ -157,24 +152,109 @@ jobs:
           new_changelog=$(echo "${changelog}" | base64 -w0)
           echo "changelog=${new_changelog}" >> $GITHUB_OUTPUT
 
+
   build-docs:
-    needs: [release-checks]
+    needs: release-checks
+    runs-on: ubuntu-latest
     if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
-    uses: ./.github/workflows/build-docs.yaml
-    with:
-      DEPLOY: true
-      VERSION: ${{ needs.release-checks.outputs.version }}
-    secrets: inherit
+    outputs:
+      artifact: docs
+      product-key: ${{ steps.docs-component.outputs.name }}
+      product-repo: ${{ steps.docs-component.outputs.repo }}
+    container: zepben/pipeline-docusaurus
+    steps:
+      - name: Install Git
+        run: |
+          apk add git zip
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - uses: actions/checkout@v4
+
+      - name: Check that title is defined in the repo
+        run: |
+          if [[ -d docs/site-config && -z $DOCS_TITLE ]]; then
+            echo "The \$DOCS_TITLE environment variable needs to be set on this repo!"
+            exit 1
+          fi
+        env:
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        shell: bash
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: sh
+
+      - name: Cache nodejs deps
+        uses: actions/cache@v4
+        with:
+          path: ~/.npm
+          key: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          VERSION: ${{ needs.release-checks.outputs.version }}
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        continue-on-error: true
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: sh
+
+      - uses: actions/upload-artifact@v4
+        if: steps.build.outcome == 'success'
+        with:
+          name: docs.zip
+          path: docs.zip
+          if-no-files-found: error
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the docusaurus build above."
+          exit 1
+        shell: sh
+
+      - name: Fetch the document component name
+        id: docs-component
+        shell: sh {0}
+        run: |
+            echo "repo=${GITHUB_REPOSITORY}" >> "${GITHUB_OUTPUT}"
+            # if product key is supplied
+            if [ "${{ inputs.product-key }}" != "productkeynotprovided" ]; then
+              echo "name=${{ inputs.product-key }}" >> "${GITHUB_OUTPUT}"
+            else
+              # parse out the product key from the repository name
+              echo "name=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d\/)" >> "${GITHUB_OUTPUT}"
+            fi
 
   deploy:
     needs: [release-checks, build-docs]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
+    container: zepben/pipeline-java-ewb
     outputs:
       artifact: ${{ steps.build.outputs.artifact }}
+      artifact-id: ${{ steps.build.outputs.artifact-id }}
+      version: ${{ steps.build.outputs.version }}
     env:
-      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-    container: zepben/pipeline-java-ewb
+      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
+      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+      NEXUS_SIGNATURE: ${{ secrets.NEXUS_SIGNATURE }}
     steps:
       - name: Work around git permission issue
         run: |
@@ -197,35 +277,21 @@ jobs:
           git checkout release
         shell: bash
 
-      - name: Set profile
-        id: profile
-        shell: bash
-        run: |
-          if [ "$(gh repo view --json isPrivate | jq .isPrivate)" == "true" ]; then
-            # private repository
-            echo "PROFILE=zepben-maven" >> ${GITHUB_ENV};
-            echo "Private repository detected, set profile to zepben-maven"
-          else 
-            # public repository
-            echo "PROFILE=maven-central" >> ${GITHUB_ENV}; 
-            echo "Public repository detected, set profile to maven-central"
-          fi
-
-      - name: Maven deploy to Central
+      - name: Maven package
         id: build
-        uses: zepben/maven-deploy-central-action@main
-        with:
-          NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-          NEXUS_RELEASE_URL: ${{ secrets.NEXUS_MAVEN_RELEASE }}
-          NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
-          ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY_B64 }}
-          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
-          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
-          PROFILE: ${{ env.PROFILE }}
+        run: |
+          artifactId=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/artifactId")
+          version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
+          artifact="${artifactId}-${version}"
+          mvn clean package -B -f pom.xml -P release -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dnexus.signature=$NEXUS_SIGNATURE
+          mkdir .artifact-$artifact
+          cp target/* -t .artifact-$artifact || :
+          rm .artifact-$artifact/original*.jar || :
+          echo "version=$(echo $version)" >> ${GITHUB_OUTPUT}
+          echo "artifact=$(echo $artifact)" >> ${GITHUB_OUTPUT}
+          echo "artifact-id=$(echo $artifactId)" >> ${GITHUB_OUTPUT}
+          echo "artifact-path=$(echo .artifact-$artifact/)" >> ${GITHUB_OUTPUT}
+        shell: bash
         continue-on-error: true
 
       - name: Upload coverage to Codecov
@@ -236,23 +302,24 @@ jobs:
         continue-on-error: true
 
       - uses: actions/upload-artifact@v4
+        id: upload
         if: steps.build.outcome == 'success'
         with:
           name: ${{ steps.build.outputs.artifact }}
           path: ${{ steps.build.outputs.artifact-path }}
+          include-hidden-files: true
           if-no-files-found: error
 
       - name: Delete release branch if deploy failed and fail
-        if: steps.build.outcome == 'failure'
+        if: steps.build.outcome == 'failure' || steps.upload.outcome == 'failure'
         run: |
           git push origin -d release
-          echo "There was an error in the mvn deploy command above."
+          echo "There was an error in the mvn package command above."
           exit 1
         shell: bash
 
   create-release:
     needs: [deploy, build-docs, release-checks]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -278,7 +345,7 @@ jobs:
           git push origin ${GITHUB_REF/refs\/heads\//}
           git tag "v${{ needs.release-checks.outputs.version }}"
           git push --tags
-          echo "tag=v${{ needs.release-checks.outputs.version }}" >> "${GITHUB_OUTPUT}"
+          echo "tag=$(echo v${{ needs.release-checks.outputs.version }})" >> "${GITHUB_OUTPUT}"
         shell: bash
         continue-on-error: true
 
@@ -316,7 +383,7 @@ jobs:
           draft: false
           prerelease: false
           files: |
-            built-artifacts/${{ needs.deploy.outputs.artifact }}
+            built-artifacts/*
         continue-on-error: true
 
       - name: Deploy documentation
@@ -325,12 +392,17 @@ jobs:
           token: ${{ secrets.CI_GITHUB_TOKEN }}
           repository: ${{ secrets.DOCS_REPO }}
           event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
-          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.component}}", "download_url": "${{github.repository}}" }'
+          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.product-key}}", "download_url": "${{needs.build-docs.outputs.product-repo}}"}'
         continue-on-error: true
+
+  # call-build-container:
+  #   needs: [build-artifact, create-release]
+  #   uses: zepben/energy-workbench-server/.github/workflows/build-release-container.yaml@main
+  #   with:
+  #     ewbRelease: ${{ needs.build-artifact.outputs.version }}
 
   update-version:
     needs: [create-release]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -356,5 +428,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          /scripts/update-version.sh --java --grow-changelog --maven --release pom.xml changelog.md
+          /scripts/update-version.sh --java --maven --release pom.xml changelog.md
         shell: bash
diff --git a/.github/workflows/maven-lib-release-with-docs.yml b/.github/workflows/maven-lib-release-with-docs.yml
--- a/.github/workflows/maven-lib-release-with-docs.yml
+++ b/.github/workflows/maven-lib-release-with-docs.yml
@@ -29,8 +29,6 @@ on:
         required: true
       NEXUS_PASSWORD: 
         required: true
-      NEXUS_SIGNATURE:
-        required: true
       NEXUS_MAVEN_SNAPSHOT:
         required: true
       NEXUS_MAVEN_RELEASE:
@@ -39,7 +37,7 @@ on:
         required: false
       SLACK_WEBHOOK:
         required: false
-      LC_URL: 
+      LC_URL:
         required: false
       ZEPBEN_GPG_KEY:
         required: false
@@ -158,22 +156,99 @@ jobs:
           echo "changelog=${new_changelog}" >> $GITHUB_OUTPUT
 
   build-docs:
-    needs: [release-checks]
+    needs: release-checks
+    runs-on: ubuntu-latest
     if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
-    uses: ./.github/workflows/build-docs.yaml
-    with:
-      DEPLOY: true
-      VERSION: ${{ needs.release-checks.outputs.version }}
-    secrets: inherit
+    outputs:
+      artifact: docs
+      product-key: ${{ steps.docs-component.outputs.name }}
+      product-repo: ${{ steps.docs-component.outputs.repo }}
+    container: zepben/pipeline-docusaurus
+    steps:
+      - name: Install Git
+        run: |
+          apk add git zip
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - uses: actions/checkout@v4
+
+      - name: Check that title is defined in the repo
+        run: |
+          if [[ -d docs/site-config && -z $DOCS_TITLE ]]; then
+            echo "The \$DOCS_TITLE environment variable needs to be set on this repo!"
+            exit 1
+          fi
+        env:
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        shell: bash
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: sh
+
+      - name: Cache nodejs deps
+        uses: actions/cache@v4
+        with:
+          path: ~/.npm
+          key: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          VERSION: ${{ needs.release-checks.outputs.version }}
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        continue-on-error: true
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: sh
+
+      - uses: actions/upload-artifact@v4
+        if: steps.build.outcome == 'success'
+        with:
+          name: docs.zip
+          path: docs.zip
+          if-no-files-found: error
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the docusaurus build above."
+          exit 1
+        shell: sh
+
+      - name: Fetch the document component name
+        id: docs-component
+        shell: sh {0}
+        run: |
+            # if product key is supplied
+            if [ "${{ inputs.product-key }}" != "productkeynotprovided" ]; then
+              echo "name=${{ inputs.product-key }}" >> "${GITHUB_OUTPUT}"
+            else
+              # parse out the product key from the repository name
+              echo "name=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d\/)" >> "${GITHUB_OUTPUT}"
+            fi
+
 
   deploy:
     needs: [release-checks, build-docs]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     outputs:
       artifact: ${{ steps.build.outputs.artifact }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     container: zepben/pipeline-java-ewb
     steps:
       - name: Work around git permission issue
@@ -201,15 +276,8 @@ jobs:
         id: profile
         shell: bash
         run: |
-          if [ "$(gh repo view --json isPrivate | jq .isPrivate)" == "true" ]; then
-            # private repository
-            echo "PROFILE=zepben-maven" >> ${GITHUB_ENV};
-            echo "Private repository detected, set profile to zepben-maven"
-          else 
-            # public repository
-            echo "PROFILE=maven-central" >> ${GITHUB_ENV}; 
-            echo "Public repository detected, set profile to maven-central"
-          fi
+          priv=${{ inputs.private }}
+          if [[ $priv == 'true' ]]; then echo "PROFILE=zepben-maven" >> ${GITHUB_ENV}; else echo "PROFILE=maven-central" >> ${GITHUB_ENV}; fi
 
       - name: Maven deploy to Central
         id: build
@@ -240,7 +308,6 @@ jobs:
         with:
           name: ${{ steps.build.outputs.artifact }}
           path: ${{ steps.build.outputs.artifact-path }}
-          if-no-files-found: error
 
       - name: Delete release branch if deploy failed and fail
         if: steps.build.outcome == 'failure'
@@ -252,7 +319,6 @@ jobs:
 
   create-release:
     needs: [deploy, build-docs, release-checks]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -278,7 +344,7 @@ jobs:
           git push origin ${GITHUB_REF/refs\/heads\//}
           git tag "v${{ needs.release-checks.outputs.version }}"
           git push --tags
-          echo "tag=v${{ needs.release-checks.outputs.version }}" >> "${GITHUB_OUTPUT}"
+          echo "::set-output name=tag::$(echo v${{ needs.release-checks.outputs.version }})"
         shell: bash
         continue-on-error: true
 
@@ -325,12 +391,11 @@ jobs:
           token: ${{ secrets.CI_GITHUB_TOKEN }}
           repository: ${{ secrets.DOCS_REPO }}
           event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
-          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.component}}", "download_url": "${{github.repository}}" }'
+          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.product-key}}", "download_url": "${{needs.build-docs.outputs.product-repo}}"}'
         continue-on-error: true
 
   update-version:
     needs: [create-release]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -356,5 +421,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          /scripts/update-version.sh --java --grow-changelog --maven --release pom.xml changelog.md
+          /scripts/update-version.sh --java --maven --release pom.xml changelog.md
         shell: bash
diff --git a/.github/workflows/npm-app-release-with-docs.yml b/.github/workflows/npm-app-release-with-docs.yml
--- a/.github/workflows/npm-app-release-with-docs.yml
+++ b/.github/workflows/npm-app-release-with-docs.yml
@@ -1,7 +1,6 @@
-# Note: default release notes file is docs/release.md.
-name: Maven Library Release + Docs
+name: NPM Static App Release
 
-on: 
+on:
   workflow_call:
     inputs:
       product-key:
@@ -19,59 +18,31 @@ on:
         required: false
         type: string
         default: "src"
-
     secrets:
+      NEXUS_NPM_REPO:
+        required: true
+      CI_NPM_TOKEN:
+        required: true
       CI_GITHUB_TOKEN:
-        required: true
-      NEXUS_MAVEN_REPO:
-        required: true
-      NEXUS_USERNAME:
-        required: true
-      NEXUS_PASSWORD: 
-        required: true
-      NEXUS_SIGNATURE:
-        required: true
-      NEXUS_MAVEN_SNAPSHOT:
-        required: true
-      NEXUS_MAVEN_RELEASE:
         required: true
       SLACK_NOTIFICATION:
         required: false
       SLACK_WEBHOOK:
         required: false
-      LC_URL: 
+      LC_URL:
         required: false
-      ZEPBEN_GPG_KEY:
-        required: false
-      MAVEN_CENTRAL_USERNAME:
-        required: false
-      MAVEN_CENTRAL_PASSWORD:
-        required: false
-      GPG_KEY_ID:
-        required: false
-      GPG_KEY_PASSWORD:
-        required: false
-      NPM_REPO:
-        required: true
-      DOCS_REPO:
-        required: true
-      DOCS_REPO_EVOLVE_WORKFLOW:
-        required: true
 
-
-
+    outputs:
+      version:
+        description: "The current released version."
+        value: ${{ jobs.build-artifact.outputs.version }}
 jobs:
   release-checks:
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
+    continue-on-error: false
     env:
-      DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
-      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
       SLACK_NOTIFICATION: YES
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     outputs:
@@ -104,14 +75,15 @@ jobs:
       - name: Release checks and update version for release
         id: check
         run: |
-          /scripts/release-checks.sh --java --maven pom.xml
-          /scripts/finalize-version.sh --java --maven pom.xml changelog.md
-          version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
-          echo "version=$version" >> "${GITHUB_OUTPUT}"
+          /scripts/release-checks.sh --js package.json
+          /scripts/finalize-version.sh --js package.json changelog.md
+          version=$(jq -r .version package.json)
+          echo "version=$version" >> $GITHUB_OUTPUT
         shell: bash
 
       - name: Check if docs present
         id: docs
+        shell: bash
         run: |
           if [ -d docs ]; then
             echo "Docs folder found, will run the build-docs job"
@@ -127,7 +99,7 @@ jobs:
         run: |
           # Make sure directories are properly ignored
           # docs/node_modules
-          git check-ignore -q docs/node_modules 
+          git check-ignore -q docs/node_modules
           if [ $? != 0 ]; then
               echo "ERROR! Make sure to add 'docs/node_modules' to .gitignore"
               echo "::error line=1::ERROR! Make sure to add 'docs/node_modules' to .gitignore"
@@ -135,7 +107,7 @@ jobs:
           fi
 
           # docs/build
-          git check-ignore -q docs/build 
+          git check-ignore -q docs/build
           if [ $? != 0 ]; then
               echo "ERROR! Make sure to add 'docs/build' to .gitignore"
               echo "::error line=1::ERROR! Make sure to add 'docs/build' to .gitignore"
@@ -144,7 +116,6 @@ jobs:
 
       - name: Test changelog format
         id: changelog
-        shell: bash
         run: |
           changelog=$(sed -n -E "/${{ steps.check.outputs.version }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" changelog.md)
           if [[ -z "$changelog" ]]; then
@@ -158,103 +129,178 @@ jobs:
           echo "changelog=${new_changelog}" >> $GITHUB_OUTPUT
 
   build-docs:
-    needs: [release-checks]
-    if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
-    uses: ./.github/workflows/build-docs.yaml
-    with:
-      DEPLOY: true
-      VERSION: ${{ needs.release-checks.outputs.version }}
-    secrets: inherit
-
-  deploy:
-    needs: [release-checks, build-docs]
-    if: always() && !failure() && !cancelled()
+    needs: release-checks
     runs-on: ubuntu-latest
+    if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
     outputs:
-      artifact: ${{ steps.build.outputs.artifact }}
+      artifact: docs
+      product-key: ${{ steps.docs-component.outputs.name }}
+      product-repo: ${{ steps.docs-component.outputs.repo }}
+    container: zepben/pipeline-docusaurus
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-    container: zepben/pipeline-java-ewb
     steps:
+
+      - uses: actions/checkout@v4
+        with:
+          token: ${{ env.GITHUB_TOKEN }}
+
       - name: Work around git permission issue
         run: |
           dname=$(echo ${{github.repository}} | cut -d'/' -f2)
           git config --global --add safe.directory /__w/$dname/$dname
         shell: sh
 
-      - uses: actions/checkout@v4
-
-      - name: Cache maven deps
-        uses: actions/cache@v4
-        with:
-          path: /maven
-          key: maven
+      - name: Check that title is defined in the repo
+        run: |
+          if [[ -d docs/site-config && -z $DOCS_TITLE ]]; then
+            echo "The \$DOCS_TITLE environment variable needs to be set on this repo!"
+            exit 1
+          fi
+        env:
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        shell: bash
 
       - name: Checkout release branch
         run: |
           git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
           git fetch --all
           git checkout release
-        shell: bash
+        shell: sh
 
-      - name: Set profile
-        id: profile
-        shell: bash
-        run: |
-          if [ "$(gh repo view --json isPrivate | jq .isPrivate)" == "true" ]; then
-            # private repository
-            echo "PROFILE=zepben-maven" >> ${GITHUB_ENV};
-            echo "Private repository detected, set profile to zepben-maven"
-          else 
-            # public repository
-            echo "PROFILE=maven-central" >> ${GITHUB_ENV}; 
-            echo "Public repository detected, set profile to maven-central"
-          fi
-
-      - name: Maven deploy to Central
-        id: build
-        uses: zepben/maven-deploy-central-action@main
+      - name: Cache nodejs deps
+        uses: actions/cache@v4
         with:
-          NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-          NEXUS_RELEASE_URL: ${{ secrets.NEXUS_MAVEN_RELEASE }}
-          NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
-          ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY_B64 }}
-          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
-          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
-          PROFILE: ${{ env.PROFILE }}
+          path: ~/.npm
+          key: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          VERSION: ${{ needs.release-checks.outputs.version }}
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
         continue-on-error: true
 
-      - name: Upload coverage to Codecov
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: sh
+
+      - uses: actions/upload-artifact@v4
         if: steps.build.outcome == 'success'
-        uses: codecov/codecov-action@v4
-        with: 
-          token: ${{ secrets.CODECOV_TOKEN }}
+        with:
+          name: docs.zip
+          path: docs.zip
+          if-no-files-found: error
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the docusaurus build above."
+          exit 1
+        shell: sh
+
+      - name: Fetch the document component name
+        id: docs-component
+        shell: sh {0}
+        run: |
+            echo "repo=${GITHUB_REPOSITORY}" >> "${GITHUB_OUTPUT}"
+            # if product key is supplied
+            if [ "${{ inputs.product-key }}" != "productkeynotprovided" ]; then
+              echo "name=${{ inputs.product-key }}" >> "${GITHUB_OUTPUT}"
+            else
+              # parse out the product key from the repository name
+              echo "name=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d\/)" >> "${GITHUB_OUTPUT}"
+            fi
+
+
+  build-artifact:
+    needs: [build-docs, release-checks]
+    runs-on: ubuntu-latest
+    container: node:20-alpine
+    outputs:
+      artifact: ${{ steps.build.outputs.artifact }}
+      artifact-id: ${{ steps.build.outputs.artifact-id }}
+      version: ${{ steps.build.outputs.version }}
+    env:
+      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+    steps:
+      - name: Install Dependencies
+        run: |
+          apk add jq tar alpine-conf git
+
+      - name: Cache nodejs deps
+        uses: actions/cache@v4
+        with:
+          path: ~/.npm
+          key: npm
+
+      - uses: actions/checkout@v4
+        with:
+          token: ${{ env.GITHUB_TOKEN }}
+
+      - name: Set timezone to Australia/ACT
+        run: |
+          setup-timezone -z Australia/ACT
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: sh
+
+      - name: create .npmrc
+        run: |
+          rm -rf .npmrc
+          echo "@zepben:registry=${{ secrets.NEXUS_NPM_REPO }}" >> .npmrc
+          echo "//nexus.z.zepben.cloud/repository/zepben-npm/:_authToken=${{ secrets.CI_NPM_TOKEN }}" >> .npmrc
+          echo "\n" >> .npmrc
+
+      - name: build
+        id: build
+        run: |
+          npm ci --unsafe-perm
+          npm run prod
+          version=$(jq -r .version package.json)
+          artifactId=$(jq -r .name package.json)
+          artifact="$artifactId-$version.tar.bz2"
+          tar jcvf "$artifact" -C dist .
+          echo "version=$version" >> "${GITHUB_OUTPUT}"
+          echo "artifact=$artifact" >> "${GITHUB_OUTPUT}"
         continue-on-error: true
 
       - uses: actions/upload-artifact@v4
         if: steps.build.outcome == 'success'
         with:
           name: ${{ steps.build.outputs.artifact }}
-          path: ${{ steps.build.outputs.artifact-path }}
-          if-no-files-found: error
+          path: ${{ steps.build.outputs.artifact }}
 
-      - name: Delete release branch if deploy failed and fail
+      - name: Fail build
         if: steps.build.outcome == 'failure'
         run: |
           git push origin -d release
-          echo "There was an error in the mvn deploy command above."
+          echo "There was an error in the npm package command above."
           exit 1
-        shell: bash
+        shell: sh
 
   create-release:
-    needs: [deploy, build-docs, release-checks]
-    if: always() && !failure() && !cancelled()
+    needs: [build-artifact]
     runs-on: ubuntu-latest
-    container: zepben/pipeline-basic
+    outputs:
+      artifact: ${{ steps.merge.outputs.artifact }}
+      tag: ${{ steps.merge.outputs.tag }}
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
@@ -268,41 +314,35 @@ jobs:
           git config --global --add safe.directory /__w/$dname/$dname
         shell: sh
 
-      - name: Merge and Tag
-        id: merge
-        run: |
-          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-          git fetch --all
-          git branch -a
-          git merge origin/release
-          git push origin ${GITHUB_REF/refs\/heads\//}
-          git tag "v${{ needs.release-checks.outputs.version }}"
-          git push --tags
-          echo "tag=v${{ needs.release-checks.outputs.version }}" >> "${GITHUB_OUTPUT}"
-        shell: bash
-        continue-on-error: true
-
-      - name: Delete release branch if merge failed and fail
-        if: steps.merge.outcome == 'failure'
-        run: |
-          git push origin -d release
-          echo "There was an error in merging the branch. release branch was deleted."
-          exit 1
-        shell: bash
-
-      - name: Download binary
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ needs.deploy.outputs.artifact }}
-          path: built-artifacts
-        continue-on-error: true
-
       - name: Get latest changelog
         id: changelog
         run: |
           echo "${{ needs.release-checks.outputs.changelog }}" | base64 -d > latest_changelog.txt
         shell: bash
         continue-on-error: true
+
+      - name: Merge and Tag
+        id: merge
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git merge origin/release
+          git push origin ${GITHUB_REF/refs\/heads\//}
+          version=$(jq -r .version package.json)
+          git tag "v$version"
+          git push --tags
+          echo "::set-output name=tag::$(echo v$version)"
+          echo "::set-output name=artifact::$(echo ${{ needs.build-artifact.outputs.artifact }})"
+        shell: bash
+        continue-on-error: true
+
+      - name: Fail
+        if: steps.merge.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in merging the branch. release branch was deleted."
+          exit 1
+        shell: bash
 
       - name: Create Release and upload assets
         if: success()
@@ -316,7 +356,7 @@ jobs:
           draft: false
           prerelease: false
           files: |
-            built-artifacts/${{ needs.deploy.outputs.artifact }}
+            built-artifacts/${{ needs.build-artifact.outputs.artifact }}
         continue-on-error: true
 
       - name: Deploy documentation
@@ -325,22 +365,16 @@ jobs:
           token: ${{ secrets.CI_GITHUB_TOKEN }}
           repository: ${{ secrets.DOCS_REPO }}
           event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
-          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.component}}", "download_url": "${{github.repository}}" }'
+          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.product-key}}", "download_url": "${{needs.build-docs.outputs.product-repo}}"}'
         continue-on-error: true
 
   update-version:
-    needs: [create-release]
-    if: always() && !failure() && !cancelled()
+    needs: create-release
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
       DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
-      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
       SLACK_NOTIFICATION: YES
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     steps:
@@ -356,5 +390,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          /scripts/update-version.sh --java --grow-changelog --maven --release pom.xml changelog.md
+          /scripts/update-version.sh --js --release package.json changelog.md
         shell: bash
diff --git a/.github/workflows/python-lib-release-with-docs.yml b/.github/workflows/python-lib-release-with-docs.yml
--- a/.github/workflows/python-lib-release-with-docs.yml
+++ b/.github/workflows/python-lib-release-with-docs.yml
@@ -1,5 +1,5 @@
 # Note: default release notes file is docs/release.md.
-name: Maven Library Release + Docs
+name: Python Library Release + Docs
 
 on: 
   workflow_call:
@@ -7,7 +7,6 @@ on:
       product-key:
         description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
         required: false
-        default: "productkeynotprovided"
         type: string
       private:
         description: 'Calling workflow from a private repo'
@@ -23,33 +22,21 @@ on:
     secrets:
       CI_GITHUB_TOKEN:
         required: true
-      NEXUS_MAVEN_REPO:
-        required: true
+      ZEPBEN_PYPI_REPO:
+        required: false
       NEXUS_USERNAME:
-        required: true
+        required: false
       NEXUS_PASSWORD: 
-        required: true
-      NEXUS_SIGNATURE:
-        required: true
-      NEXUS_MAVEN_SNAPSHOT:
-        required: true
-      NEXUS_MAVEN_RELEASE:
-        required: true
+        required: false
       SLACK_NOTIFICATION:
         required: false
       SLACK_WEBHOOK:
         required: false
-      LC_URL: 
+      LC_URL:
         required: false
-      ZEPBEN_GPG_KEY:
+      COVERALLS_REPO_TOKEN:
         required: false
-      MAVEN_CENTRAL_USERNAME:
-        required: false
-      MAVEN_CENTRAL_PASSWORD:
-        required: false
-      GPG_KEY_ID:
-        required: false
-      GPG_KEY_PASSWORD:
+      PYPI_API_TOKEN:
         required: false
       NPM_REPO:
         required: true
@@ -67,12 +54,7 @@ jobs:
     env:
       DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
-      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
-      SLACK_NOTIFICATION: YES
+      SLACK_NOTIFICATION: ${{ secrets.SLACK_NOTIFICATION }}
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     outputs:
       version: ${{ steps.check.outputs.version }}
@@ -89,6 +71,15 @@ jobs:
           git config --global --add safe.directory /__w/$dname/$dname
         shell: sh
 
+      - name: Release checks and update version for release
+        id: check
+        run: |
+          /scripts/release-checks.sh --python pyproject.toml
+          /scripts/finalize-version.sh --python pyproject.toml
+          version="$(cat pyproject.toml | grep 'version[[:space:]]*=[[:space:]]*"\?[0-9]\+\.[0-9]\+\.[0-9]\+\(b[0-9]\+\)\?"\?' | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+\(b[0-9]\+\)\?")"
+          echo "version=$version" >> "${GITHUB_OUTPUT}"
+        shell: bash
+
       - name: Cache licence-check
         uses: actions/cache@v4
         with:
@@ -100,15 +91,6 @@ jobs:
         with:
           LC_URL: ${{ secrets.LC_URL }}
           PATH: ${{ inputs.sourcepath }}
-
-      - name: Release checks and update version for release
-        id: check
-        run: |
-          /scripts/release-checks.sh --java --maven pom.xml
-          /scripts/finalize-version.sh --java --maven pom.xml changelog.md
-          version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
-          echo "version=$version" >> "${GITHUB_OUTPUT}"
-        shell: bash
 
       - name: Check if docs present
         id: docs
@@ -157,25 +139,34 @@ jobs:
           new_changelog=$(echo "${changelog}" | base64 -w0)
           echo "changelog=${new_changelog}" >> $GITHUB_OUTPUT
 
-  build-docs:
-    needs: [release-checks]
-    if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
-    uses: ./.github/workflows/build-docs.yaml
-    with:
-      DEPLOY: true
-      VERSION: ${{ needs.release-checks.outputs.version }}
-    secrets: inherit
-
-  deploy:
-    needs: [release-checks, build-docs]
-    if: always() && !failure() && !cancelled()
+  python-deps-check:
+    needs: release-checks
     runs-on: ubuntu-latest
-    outputs:
-      artifact: ${{ steps.build.outputs.artifact }}
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-    container: zepben/pipeline-java-ewb
+    container: python:3.10
     steps:
+      - uses: actions/checkout@v4
+
+      - name: Test install the local package with deps
+        run: |
+          # finalize-version above removes all snapshot/test versions
+          # from zepben packages. Now let's try to install to see if deps exist or fail quick
+          pip install --pre '.'
+
+
+  build-docs:
+    needs: [release-checks, python-deps-check]
+    runs-on: ubuntu-latest
+    if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
+    outputs:
+      artifact: docs
+      product-key: ${{ steps.docs-component.outputs.name }}
+      product-repo: ${{ steps.docs-component.outputs.repo }}
+    container: zepben/pipeline-docusaurus
+    steps:
+      - name: Install Git
+        run: |
+          apk add git zip
+
       - name: Work around git permission issue
         run: |
           dname=$(echo ${{github.repository}} | cut -d'/' -f2)
@@ -184,75 +175,146 @@ jobs:
 
       - uses: actions/checkout@v4
 
-      - name: Cache maven deps
-        uses: actions/cache@v4
-        with:
-          path: /maven
-          key: maven
+      - name: Check that title is defined in the repo
+        run: |
+          if [[ -d docs/site-config && -z $DOCS_TITLE ]]; then
+            echo "The \$DOCS_TITLE environment variable needs to be set on this repo!"
+            exit 1
+          fi
+        env:
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        shell: bash
 
       - name: Checkout release branch
         run: |
           git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
           git fetch --all
           git checkout release
-        shell: bash
+        shell: sh
 
-      - name: Set profile
-        id: profile
-        shell: bash
-        run: |
-          if [ "$(gh repo view --json isPrivate | jq .isPrivate)" == "true" ]; then
-            # private repository
-            echo "PROFILE=zepben-maven" >> ${GITHUB_ENV};
-            echo "Private repository detected, set profile to zepben-maven"
-          else 
-            # public repository
-            echo "PROFILE=maven-central" >> ${GITHUB_ENV}; 
-            echo "Public repository detected, set profile to maven-central"
-          fi
-
-      - name: Maven deploy to Central
-        id: build
-        uses: zepben/maven-deploy-central-action@main
+      - name: Cache nodejs deps
+        uses: actions/cache@v4
         with:
-          NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-          NEXUS_RELEASE_URL: ${{ secrets.NEXUS_MAVEN_RELEASE }}
-          NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
-          ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY_B64 }}
-          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
-          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
-          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
-          PROFILE: ${{ env.PROFILE }}
+          path: ~/.npm
+          key: npm
+
+      - name: Build docusaurus
+        id: build
+        uses: zepben/docusaurus-action@main
+        with:
+          VERSION: ${{ needs.release-checks.outputs.version }}
+          NPM_REPO: ${{ secrets.NPM_REPO }}
+          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+          DOCS_TITLE: ${{ vars.DOCS_TITLE }}
+        continue-on-error: true
+
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: sh
+
+      - uses: actions/upload-artifact@v4
+        if: steps.build.outcome == 'success'
+        with:
+          name: docs.zip
+          path: docs.zip
+          if-no-files-found: error
+
+      - name: Fail build
+        if: steps.build.outcome == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the docusaurus build above."
+          exit 1
+        shell: sh
+
+      - name: Fetch the document component name
+        id: docs-component
+        shell: sh {0}
+        run: |
+            echo "repo=${GITHUB_REPOSITORY}" >> "${GITHUB_OUTPUT}"
+            # if product key is supplied
+            if [ "${{ inputs.product-key }}" != "productkeynotprovided" ]; then
+              echo "name=${{ inputs.product-key }}" >> "${GITHUB_OUTPUT}"
+            else
+              # parse out the product key from the repository name
+              echo "name=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d\/)" >> "${GITHUB_OUTPUT}"
+            fi
+
+
+
+  deploy:
+    needs: [release-checks, build-docs]
+    runs-on: ubuntu-latest
+    container: python:3.10
+    outputs:
+      artifact: ${{ steps.build.outputs.artifact }}
+    steps:
+      - name: Install dependencies
+        run: |
+          pip install tox twine
+
+      - name: Work around git permission issue
+        run: |
+          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
+          git config --global --add safe.directory /__w/$dname/$dname
+        shell: sh
+
+      - uses: actions/checkout@v4
+
+      - name: Checkout release branch
+        run: |
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git checkout release
+        shell: sh
+
+      - name: Create .pypirc
+        env:
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+        run: |
+          echo "[pypi]" > ~/.pypirc
+          echo "username = __token__" >> ~/.pypirc
+          echo "password = $PYPI_API_TOKEN" >> ~/.pypirc
+          echo "\n" >> ~/.pypirc
+
+      - name: Build and publish
+        id: build
+        run: |
+          tox
+          twine upload --non-interactive --config-file ~/.pypirc dist/*
+          artifact_id=$(grep name= pyproject.toml | cut -d= -f2 | tr -d '",' | sed 's-\.-_-g')
+          artifact="${artifact_id}-${{ needs.release-checks.outputs.version }}-py3-none-any.whl"
+          echo "::set-output name=artifact::$(echo $artifact)"
+          echo "::set-output name=artifact-path::$(echo dist/$artifact)"
+        shell: bash
         continue-on-error: true
 
       - name: Upload coverage to Codecov
-        if: steps.build.outcome == 'success'
         uses: codecov/codecov-action@v4
-        with: 
+        with:
+          fail_ci_if_error: false
           token: ${{ secrets.CODECOV_TOKEN }}
         continue-on-error: true
+          
 
       - uses: actions/upload-artifact@v4
         if: steps.build.outcome == 'success'
         with:
           name: ${{ steps.build.outputs.artifact }}
           path: ${{ steps.build.outputs.artifact-path }}
-          if-no-files-found: error
 
       - name: Delete release branch if deploy failed and fail
         if: steps.build.outcome == 'failure'
         run: |
           git push origin -d release
-          echo "There was an error in the mvn deploy command above."
+          echo "There was an error in the python build and publish commands above."
           exit 1
         shell: bash
 
   create-release:
     needs: [deploy, build-docs, release-checks]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
@@ -278,7 +340,7 @@ jobs:
           git push origin ${GITHUB_REF/refs\/heads\//}
           git tag "v${{ needs.release-checks.outputs.version }}"
           git push --tags
-          echo "tag=v${{ needs.release-checks.outputs.version }}" >> "${GITHUB_OUTPUT}"
+          echo "::set-output name=tag::$(echo v${{ needs.release-checks.outputs.version }})"
         shell: bash
         continue-on-error: true
 
@@ -325,23 +387,20 @@ jobs:
           token: ${{ secrets.CI_GITHUB_TOKEN }}
           repository: ${{ secrets.DOCS_REPO }}
           event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
-          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.component}}", "download_url": "${{github.repository}}" }'
+          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.product-key}}", "download_url": "${{needs.build-docs.outputs.product-repo}}"}'
         continue-on-error: true
 
   update-version:
     needs: [create-release]
-    if: always() && !failure() && !cancelled()
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
     env:
       DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
-      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
-      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
-      SLACK_NOTIFICATION: YES
+      ZEPBEN_PYPI_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+      ZEPBEN_PYPI_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+      ZEPBEN_PYPI_REPO: ${{ secrets.ZEPBEN_PYPI_REPO }}
+      SLACK_NOTIFICATION: ${{ secrets.SLACK_NOTIFICATION }}
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     steps:
       - uses: actions/checkout@v4
@@ -356,5 +415,5 @@ jobs:
 
       - name: Update to next minor version
         run: |
-          /scripts/update-version.sh --java --grow-changelog --maven --release pom.xml changelog.md
+          /scripts/update-version.sh --python --release pyproject.toml changelog.md
         shell: bash
