lint using the default eslint dependencies and fall back on the repository level linting using npm run
Signed-off-by: conner-zepben <159741171+conner-zepben@users.noreply.github.com>

diff --git a/.github/workflows/npm-app-snapshot-release.yml b/.github/workflows/npm-app-snapshot-release.yml
--- a/.github/workflows/npm-app-snapshot-release.yml
+++ b/.github/workflows/npm-app-snapshot-release.yml
@@ -87,6 +87,27 @@ jobs:
         echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_GITHUB_TOKEN }}" >> ~/.npmrc
         echo "\n" >> ~/.npmrc
 
+    - name: Install linting dependencies
+      run: |
+        npm install eslint@latest typescript@latest @typescript-eslint/parser@latest @typescript-eslint/eslint-plugin@latest
+
+    - name: Default Linting
+      id: lint_shared
+      continue-on-error: true
+      run: |
+        npx eslint --ext .ts,.js,.tsx,.jsx .
+
+    - name: 
+      if: steps.lint_shared.outcome == 'failure'
+      run: |
+        if npm run | grep -q 'lint'; then
+          echo "Executing repository-specific lint script..."
+          npm run lint
+        else
+          echo "ERROR! No repository-specific lint script found, failing the build."
+          exit 1
+        fi
+
     - name: build
       id: build
       run: |
