[OPS-510] Overhaul docs building (#101)
* Refactor docs building

This change refactors how we build the documentation:

- Introduce a new workflow, build-docs that calls docusaurus-action and builds the docs.
  - It can also optionally "version tag" the docs
  - It can also "deploy" the docs (ie build the zipped archive for later deployment).
- It introduces the use of a new environment parameter called PRODUCT (to differentiate the deployment of evolve and ednar).

Other workflows were adapted to use this new flow.

The benefit of this refactoring is that all aspects of the documentation building are now controlled centrally via 1 flow.
Additionally, it allows to easily create separate, stand-alone docs-deployment flows.

Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/npm-lib-release.yml b/.github/workflows/npm-lib-release.yml
--- a/.github/workflows/npm-lib-release.yml
+++ b/.github/workflows/npm-lib-release.yml
@@ -34,6 +34,7 @@ jobs:
     continue-on-error: false
     outputs:
       changelog: ${{ steps.changelog.outputs.changelog }}
+      version: ${{ steps.version.outputs.version }}
     env:
       DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
@@ -94,6 +95,7 @@ jobs:
       artifact: ${{ steps.build.outputs.artifact }}
       artifact-id: ${{ steps.build.outputs.artifact-id }}
       version: ${{ steps.build.outputs.version }}
+      docs-present: ${{ steps.docs.outputs.present }}
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
@@ -147,8 +149,8 @@ jobs:
           artifact="$(npm pack --foreground-scripts=false --json --dry-run | jq -r .[0].filename)"
           npm publish
           version=$(jq -r .version package.json)
-          echo "::set-output name=version::$(echo $version)"
-          echo "::set-output name=artifact::$(echo $artifact)"
+          echo "version=$version" >> "${GITHUB_OUTPUT}"
+          echo "artifact=$artifact" >> "${GITHUB_OUTPUT}" 
         continue-on-error: true
 
       - uses: actions/upload-artifact@v4
@@ -166,6 +168,38 @@ jobs:
           exit 1
         shell: sh
 
+      - name: Check if docs present
+        id: docs
+        run: |
+          if [ -d docs ]; then
+            echo "Docs folder found, will run the build-docs job"
+            echo "present=yes" >> "${GITHUB_OUTPUT}"
+            echo "present=yes" >> "${GITHUB_ENV}"
+          else
+            echo "Docs folder not found, will skip the build-docs"
+          fi
+
+      - name: Check doc build artifacts are ignored
+        if: ${{ env.present == 'yes' }}
+        shell: sh {0}
+        run: |
+          # Make sure directories are properly ignored
+          # docs/node_modules
+          git check-ignore -q docs/site-config/project.json
+          if [ $? != 0 ]; then
+              echo "ERROR! Make sure to add 'docs/site-config' to .gitignore"
+              echo "::error line=1::ERROR! Make sure to add 'docs/site-config' to .gitignore"
+              exit 1
+          fi
+
+  build-docs:
+    needs: [build-artifact]
+    if: ${{ needs.build-artifact.outputs.docs-present == 'yes' }}
+    uses: ./.github/workflows/build-docs.yaml
+    with:
+      DEPLOY: true
+    secrets: inherit
+
   create-release:
     needs: [build-artifact, release-checks]
     runs-on: ubuntu-latest
@@ -174,7 +208,6 @@ jobs:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     outputs:
       artifact: ${{ steps.merge.outputs.artifact }}
-      tag: ${{ steps.merge.outputs.tag }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -213,10 +246,9 @@ jobs:
           git fetch --all
           git merge origin/release
           git push origin ${GITHUB_REF/refs\/heads\//}
-          version=$(jq -r .version package.json)
-          git tag "v$version"
+          git tag "v${{ needs.release-checks.outputs.version }}"
           git push --tags
-          echo "tag=v$version" >> $GITHUB_OUTPUT
+          echo "tag=v${{ needs.release-checks.outputs.version }}" >> $GITHUB_OUTPUT
           echo "artifact=${{ needs.build-artifact.outputs.artifact }}" >> $GITHUB_OUTPUT
         shell: bash
         continue-on-error: true
@@ -277,3 +309,17 @@ jobs:
         run: |
           /scripts/update-version.sh --js --release --grow-changelog package.json changelog.md
         shell: bash
+
+  deploy-docs:
+    runs-on: ubuntu-latest
+    needs: [build-docs]
+    if: ${{ needs.build-docs.outputs.artifact-uploaded == 'yes' }}
+    steps:
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v2
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product": "${{needs.build-docs.outputs.product}}", "product_key": "${{needs.build-docs.outputs.component}}", "download_url": "${{github.repository}}"}'
+
