Use sed instead of cat/head/tail
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/npm-app-release.yml b/.github/workflows/npm-app-release.yml
--- a/.github/workflows/npm-app-release.yml
+++ b/.github/workflows/npm-app-release.yml
@@ -168,9 +168,18 @@ jobs:
           lines=$(egrep -n "## \[[0-9]+\.[0-9]+\.[0-9]+\]" changelog.md | head -2 | cut -f1 -d:)
           line1=$(echo "$lines" | head -1)
           line2=$(echo "$lines" | tail -1)
-          cat changelog.md | tail -n +$((line1+1)) | head -n $((line2-line1-1)) > latest_changelog.txt
+          # Fetch lines line1+1 to line2-1 from the changelog.md and save to another file
+          sed -n "$((line1+1)),$((line2-1))p" changelog.md > latest_changelog.txt
         shell: bash
         continue-on-error: true
+
+      - name: Fail Release
+        if: steps.changelog.outcome == 'failure'
+        run: | 
+          git push origin -d release
+          echo "There was an error generating a changelog above."
+          exit 1
+        shell: sh
 
       - name: Download artifact
         uses: actions/download-artifact@v2
