[OPS-195] Fail the npm-lib-release workflow sooner if no build artifact exists (#30)
* Fail the upload-artifact step if no files were found to upload
* Download the artefact before git tagging and fail if it doesn't exist

Signed-off-by: Josh Leyshon <josh.leyshon@zepben.com>
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/npm-app-release-with-docs.yml b/.github/workflows/npm-app-release-with-docs.yml
--- a/.github/workflows/npm-app-release-with-docs.yml
+++ b/.github/workflows/npm-app-release-with-docs.yml
@@ -126,6 +126,7 @@ jobs:
         with:
           name: docs
           path: docs/build/
+          if-no-files-found: error
 
       - name: Fail build
         if: steps.build.outcome == 'failure'
@@ -230,36 +231,6 @@ jobs:
           git config --global --add safe.directory /__w/$dname/$dname
         shell: sh
 
-      - name: Merge and Tag
-        id: merge
-        run: | 
-          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-          git fetch --all
-          git merge origin/release
-          git push origin ${GITHUB_REF/refs\/heads\//}
-          version=$(jq -r .version package.json)
-          git tag "v$version"
-          git push --tags
-          echo "::set-output name=tag::$(echo v$version)"
-          echo "::set-output name=artifact::$(echo ${{ needs.build-artifact.outputs.artifact }})"
-        shell: bash
-        continue-on-error: true
-
-      - name: Fail
-        if: steps.merge.outcome == 'failure'
-        run: | 
-          git push origin -d release
-          echo "There was an error in merging the branch. release branch was deleted."
-          exit 1
-        shell: bash
-
-      - name: Download binary
-        uses: actions/download-artifact@v3
-        with:
-          name: ${{ needs.build-artifact.outputs.artifact }}
-          path: built-artifacts
-        continue-on-error: true
-
       - name: Download docs
         uses: actions/download-artifact@v3
         with:
@@ -283,6 +254,29 @@ jobs:
           cat changelog.md | tail -n +$((line1+1)) | head -n $((line2-line1-1)) > latest_changelog.txt
         shell: bash
         continue-on-error: true
+
+      - name: Merge and Tag
+        id: merge
+        run: | 
+          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+          git fetch --all
+          git merge origin/release
+          git push origin ${GITHUB_REF/refs\/heads\//}
+          version=$(jq -r .version package.json)
+          git tag "v$version"
+          git push --tags
+          echo "::set-output name=tag::$(echo v$version)"
+          echo "::set-output name=artifact::$(echo ${{ needs.build-artifact.outputs.artifact }})"
+        shell: bash
+        continue-on-error: true
+
+      - name: Fail
+        if: steps.merge.outcome == 'failure'
+        run: | 
+          git push origin -d release
+          echo "There was an error in merging the branch. release branch was deleted."
+          exit 1
+        shell: bash
 
       - name: Create Release and upload assets
         if: success()
