Improve changelog processing
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>

diff --git a/.github/workflows/npm-app-release.yml b/.github/workflows/npm-app-release.yml
--- a/.github/workflows/npm-app-release.yml
+++ b/.github/workflows/npm-app-release.yml
@@ -49,6 +49,7 @@ jobs:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     outputs:
       version: ${{ steps.check.outputs.version }}
+      changelog: ${{ steps.changelog.outputs.changelog }}
     steps:
       - uses: actions/checkout@v3
         with:
@@ -82,6 +83,17 @@ jobs:
           version=$(jq -r .version package.json)
           echo "version=$version" >> $GITHUB_OUTPUT
         shell: bash
+
+      - name: Test changelog format
+        id: changelog
+        run: |
+          changelog=$(sed -n -E "/${{ steps.check.outputs.version }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" changelog.md)
+          if [[ -z "$changelog" ]]; then
+            echo "Changelog content was not found - ensure your changelog.md matches the expected growing format. Deleting release branch."
+            git push origin -d release
+            exit 1
+          fi
+          echo "changelog=$changelog" >> $GITHUB_OUTPUT
 
   build-docs:
     needs: release-checks
@@ -184,17 +196,6 @@ jobs:
           git checkout release
         shell: sh
 
-      - name: Test changelog format
-        id: changelog
-        run: |
-          changelog=$(sed -n -E "/${{ needs.release-checks.outputs.version }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" changelog.md)
-          if [[ -z "$changelog" ]]; then
-            echo "Changelog content was not found - ensure your changelog.md matches the expected growing format. Deleting release branch."
-            git push origin -d release
-            exit 1
-          fi
-        continue-on-error: false
-
       - name: create .npmrc
         run: | 
           rm -rf .npmrc
@@ -273,15 +274,17 @@ jobs:
       - name: Get latest changelog
         id: changelog
         run: |
-          sed -n -E "/${{ needs.release-checks.outputs.version }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" changelog.md > latest_changelog.txt
+          echo "${{ needs.release-checks.outputs.changelog }}" > latest_changelog.txt
         shell: bash
         continue-on-error: true
 
-      - name: Fail Release
+      - name: Tell user to release themselves
         if: steps.changelog.outcome == 'failure'
         run: | 
-          git push origin -d release
-          echo "There was an error generating a changelog above."
+          echo "There was an error generating a changelog to associate with the release (see previous step and step in release-checks). You'll need to:"
+          echo "1. Fix the changelog"
+          echo "2. Manually create the release"
+          echo "3. Update to the next snapshot version."
           exit 1
         shell: sh
 
