'release-with-docs' flows are going away. Enough is enough
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

diff --git a/.github/workflows/npm-app-release.yml b/.github/workflows/npm-app-release.yml
--- a/.github/workflows/npm-app-release.yml
+++ b/.github/workflows/npm-app-release.yml
@@ -3,6 +3,11 @@ name: NPM Static App Release
 on:
   workflow_call:
     inputs:
+      product-key:
+        description: 'Product key used for deploying docs. Should be repo specific. E.g: "python-sdk"'
+        required: false
+        default: "productkeynotprovided"
+        type: string
       private:
         description: 'Calling workflow from a private repo'
         required: false
@@ -37,14 +42,13 @@ jobs:
     container: zepben/pipeline-basic
     continue-on-error: false
     env:
-      DEBUG: ${{ secrets.DEBUG }}
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
       SLACK_NOTIFICATION: YES
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     outputs:
       version: ${{ steps.check.outputs.version }}
-      changelog: ${{ steps.changelog.outputs.changelog }}
       docs-present: ${{ steps.docs.outputs.present }}
+      changelog: ${{ steps.changelog.outputs.changelog }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -77,21 +81,9 @@ jobs:
           echo "version=$version" >> $GITHUB_OUTPUT
         shell: bash
 
-      - name: Test changelog format
-        id: changelog
-        run: |
-          changelog=$(sed -n -E "/${{ steps.check.outputs.version }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" changelog.md)
-          if [[ -z "$changelog" ]]; then
-            echo "Changelog content was not found - ensure your changelog.md matches the expected growing format. Deleting release branch."
-            git push origin -d release
-            exit 1
-          fi
-          # Changelog has newlines which isn't well supported, so we base64 with line wrap disabled (-w0)
-          new_changelog=$(echo "${changelog}" | base64 -w0)
-          echo "changelog=${new_changelog}" >> $GITHUB_OUTPUT
-
       - name: Check if docs present
         id: docs
+        shell: bash
         run: |
           if [ -d docs ]; then
             echo "Docs folder found, will run the build-docs job"
@@ -122,19 +114,35 @@ jobs:
               exit 1
           fi
 
+      - name: Test changelog format
+        id: changelog
+        run: |
+          changelog=$(sed -n -E "/${{ steps.check.outputs.version }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" changelog.md)
+          if [[ -z "$changelog" ]]; then
+            echo "Changelog content was not found - ensure your changelog.md matches the expected growing format. Deleting release branch."
+            git push origin -d release
+            # We can safely fail here because we haven't done anything yet. Changelog.md file should be in correct format.
+            exit 1
+          fi
+          # Changelog has newlines which isn't well supported, so we base64 with line wrap disabled (-w0)
+          new_changelog=$(echo "${changelog}" | base64 -w0)
+          echo "changelog=${new_changelog}" >> $GITHUB_OUTPUT
+
   build-docs:
     needs: release-checks
-    if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
     runs-on: ubuntu-latest
+    if: ${{ needs.release-checks.outputs.docs-present == 'yes' }}
     outputs:
       artifact: docs
+      product-key: ${{ steps.docs-component.outputs.name }}
+      product-repo: ${{ steps.docs-component.outputs.repo }}
     container: node:20-alpine
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
       - name: Install Git
         run: |
-          apk add git tar
+          apk add git zip
 
       - name: Work around git permission issue
         run: |
@@ -168,11 +176,17 @@ jobs:
           NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
         continue-on-error: true
 
+      - name: Zip documentation
+        run: |
+          cd docs/build
+          zip -r ../../docs.zip .
+        shell: sh
+
       - uses: actions/upload-artifact@v4
         if: steps.build.outcome == 'success'
         with:
-          name: docs
-          path: docs/build/
+          name: docs.zip
+          path: docs.zip
           if-no-files-found: error
 
       - name: Fail build
@@ -183,13 +197,38 @@ jobs:
           exit 1
         shell: sh
 
+      - name: Fetch the document component name
+        id: docs-component
+        shell: sh {0}
+        run: |
+            echo "repo=${GITHUB_REPOSITORY}" >> "${GITHUB_OUTPUT}"
+            # if product key is supplied
+            if [ "${{ inputs.product-key }}" != "productkeynotprovided" ]; then
+              echo "name=${{ inputs.product-key }}" >> "${GITHUB_OUTPUT}"
+            else
+              # This is just so we know that we can parse the docs component properly
+              if [ -f docs/docusaurus.config.js ]; then
+                # Parse out the baseUrl from the docusaurus configuration.
+                baseurl=$(grep baseUrl docs/docusaurus.config.js | sed -e "s#/\",##g")
+                # Find the component name
+                doc_comp=${baseurl##*/}
+                echo "name=${doc_comp}" >> "${GITHUB_OUTPUT}"
+              else
+                  echo "Docs folder exists, but there's no docusaurus.config.js; check your code!"
+                  echo " :boom: Docs folder exists, but there's no docusaurus.config.js; check your code!" >> "${GITHUB_STEP_SUMMARY}"
+                  exit 1
+              fi
+            fi
+
+
   build-artifact:
-    if: ${{ !failure() }}
     needs: [build-docs, release-checks]
     runs-on: ubuntu-latest
     container: node:20-alpine
     outputs:
       artifact: ${{ steps.build.outputs.artifact }}
+      artifact-id: ${{ steps.build.outputs.artifact-id }}
+      version: ${{ steps.build.outputs.version }}
     env:
       GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
@@ -233,16 +272,15 @@ jobs:
 
       - name: build
         id: build
-        env:
-          HUSKY: 0
         run: |
-          echo "NPM is sensitive to .npmrc formatting; check that it has a newline at the end!!!"
           npm ci --unsafe-perm
           npm run prod
+          version=$(jq -r .version package.json)
           artifactId=$(jq -r .name package.json)
-          artifact="$artifactId-$${{ needs.release-checks.outputs.version }}.tar.bz2"
+          artifact="$artifactId-$version.tar.bz2"
           tar jcvf "$artifact" -C dist .
-          echo "artifact=$artifact" >> $GITHUB_OUTPUT
+          echo "version=$version" >> "${GITHUB_OUTPUT}"
+          echo "artifact=$artifact" >> "${GITHUB_OUTPUT}"
         continue-on-error: true
 
       - uses: actions/upload-artifact@v4
@@ -260,15 +298,13 @@ jobs:
         shell: sh
 
   create-release:
-    if: ${{ !failure() }}
-    needs: [build-artifact, release-checks]
+    needs: [build-artifact]
     runs-on: ubuntu-latest
-    container: zepben/pipeline-basic
-    env:
-      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     outputs:
       artifact: ${{ steps.merge.outputs.artifact }}
       tag: ${{ steps.merge.outputs.tag }}
+    env:
+      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -311,7 +347,8 @@ jobs:
         if: steps.merge.outcome == 'failure'
         run: |
           git push origin -d release
-          echo "There was an error in merging the branch. release branch was deleted."
+          echo "There was an error in merging the releae branch. It was deleted, check errors"
+          echo " :boom: There was an error in merging the releae branch. It was deleted, check errors!" >> "${GITHUB_STEP_SUMMARY}"
           exit 1
         shell: bash
 
@@ -355,8 +392,15 @@ jobs:
           exit 1
         shell: sh
 
+      - name: Deploy documentation
+        uses: peter-evans/repository-dispatch@v1
+        with:
+          token: ${{ secrets.CI_GITHUB_TOKEN }}
+          repository: ${{ secrets.DOCS_REPO }}
+          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
+          client-payload: '{"product_key": "${{needs.build-docs.outputs.product-key}}", "download_url": "${{needs.build-docs.outputs.product-repo}}"}'
+
   update-version:
-    if: ${{ !failure() }}
     needs: create-release
     runs-on: ubuntu-latest
     container: zepben/pipeline-basic
