test linter
Signed-off-by: conner-zepben <159741171+conner-zepben@users.noreply.github.com>

diff --git a/.github/workflows/npm-app-build.yml b/.github/workflows/npm-app-build.yml
--- a/.github/workflows/npm-app-build.yml
+++ b/.github/workflows/npm-app-build.yml
@@ -84,17 +84,17 @@ jobs:
           pwd
           ls -a
           npm install --save-dev --legacy-peer-deps
-          
+
       - name: Lint
         id: lint_shared
         run: |
-        if npm run | grep -q 'lint'; then
-          echo "Executing repository-specific lint script..."
-          npm run lint
-        else
-          echo "ERROR! No repository-specific lint script found, failing the build."
-          exit 1
-        fi
+          if npm run | grep -q 'lint'; then
+            echo "Executing repository-specific lint script..."
+            npm run lint
+          else
+            echo "ERROR! No repository-specific lint script found, failing the build."
+            exit 1
+          fi
 
       - name: Build and test
         run: |
