test linter
Signed-off-by: conner-zepben <159741171+conner-zepben@users.noreply.github.com>

diff --git a/.github/workflows/npm-lib-snapshot.yml b/.github/workflows/npm-lib-snapshot.yml
--- a/.github/workflows/npm-lib-snapshot.yml
+++ b/.github/workflows/npm-lib-snapshot.yml
@@ -86,25 +86,19 @@ jobs:
         echo "//mavenrepo.zepben.com/repository/zepben-npm/:_authToken=${{ secrets.CI_NPM_TOKEN }}" >> .npmrc
         echo "\n" >> .npmrc
 
-    - name: Install linting dependencies
-      run: |
-        npm install eslint@latest typescript@latest @typescript-eslint/parser@latest @typescript-eslint/eslint-plugin@latest --legacy-peer-deps
+    - name: Install Dependencies
+      run: 
+        npm install --save-dev --legacy-peer-deps
 
-    - name: Default Linting
-      id: lint_shared
+    - name: Lint
+      id: ci_lint
       continue-on-error: true
       run: |
-        npx eslint .
-
-    - name: 
-      if: steps.lint_shared.outcome == 'failure'
-      run: |
-        if npm run | grep -q 'lint'; then
-          echo "Executing repository-specific lint script..."
+        echo "Running default linting..."
+        if ! npm run lint; then
+          echo "eslint-plugin-import not found, installing and retrying..."
+          npm install eslint-plugin-import@latest --save-dev
           npm run lint
-        else
-          echo "ERROR! No repository-specific lint script found, failing the build."
-          exit 1
         fi
 
     - name: build
