delete release branch on failure
Signed-off-by: Max Chesterfield <max.chesterfield@zepben.com>

diff --git a/.github/workflows/python-lib-release.yml b/.github/workflows/python-lib-release.yml
--- a/.github/workflows/python-lib-release.yml
+++ b/.github/workflows/python-lib-release.yml
@@ -430,3 +430,23 @@ jobs:
       PRODUCT: ${{ needs.build-docs.outputs.product }}
       ARTIFACT: ${{ needs.build-docs.outputs.artifact }}
     secrets: inherit
+
+
+  delete-release-branch:
+    needs: [create-release, update-version]
+    if: failure()
+    runs-on: ubuntu-latest
+    container: zepben/pipeline-basic
+    env:
+      DEBUG: ${{ secrets.DEBUG }}
+      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+      SLACK_NOTIFICATION: ${{ secrets.SLACK_NOTIFICATION }}
+      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+    steps:
+      - name: Delete release branch
+        run: |
+          git push origin -d release
+          echo "There was an error in merging the branch. release branch was deleted."
+          exit 1
+        shell: bash
+
